// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, workspace_id, name, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, current_version_id, created_by, created_at, updated_at
`

type CreateAgentParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	CreatedBy   uuid.UUID
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.CreatedBy,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentVersion = `-- name: CreateAgentVersion :one
INSERT INTO agent_versions (
    id, agent_id, workspace_id, version, provider, model, capabilities, tool_policy, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, agent_id, workspace_id, version, provider, model, capabilities, tool_policy, created_by, created_at
`

type CreateAgentVersionParams struct {
	ID           uuid.UUID
	AgentID      uuid.UUID
	WorkspaceID  uuid.UUID
	Version      int32
	Provider     string
	Model        string
	Capabilities []string
	ToolPolicy   []byte
	CreatedBy    uuid.UUID
}

// Append-only: there is no update or delete for this table, and the triggers
// refuse both. Editing a profile means writing another row.
func (q *Queries) CreateAgentVersion(ctx context.Context, arg CreateAgentVersionParams) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, createAgentVersion,
		arg.ID,
		arg.AgentID,
		arg.WorkspaceID,
		arg.Version,
		arg.Provider,
		arg.Model,
		arg.Capabilities,
		arg.ToolPolicy,
		arg.CreatedBy,
	)
	var i AgentVersion
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.Version,
		&i.Provider,
		&i.Model,
		&i.Capabilities,
		&i.ToolPolicy,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentForWorkspace = `-- name: GetAgentForWorkspace :one
SELECT id, workspace_id, name, current_version_id, created_by, created_at, updated_at FROM agents
WHERE id = $1 AND workspace_id = $2
`

type GetAgentForWorkspaceParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetAgentForWorkspace(ctx context.Context, arg GetAgentForWorkspaceParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentForWorkspace, arg.ID, arg.WorkspaceID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentVersionForWorkspace = `-- name: GetAgentVersionForWorkspace :one
SELECT id, agent_id, workspace_id, version, provider, model, capabilities, tool_policy, created_by, created_at FROM agent_versions
WHERE id = $1 AND workspace_id = $2
`

type GetAgentVersionForWorkspaceParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetAgentVersionForWorkspace(ctx context.Context, arg GetAgentVersionForWorkspaceParams) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, getAgentVersionForWorkspace, arg.ID, arg.WorkspaceID)
	var i AgentVersion
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.WorkspaceID,
		&i.Version,
		&i.Provider,
		&i.Model,
		&i.Capabilities,
		&i.ToolPolicy,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentVersionsForWorkspace = `-- name: ListAgentVersionsForWorkspace :many
SELECT id, agent_id, workspace_id, version, provider, model, capabilities, tool_policy, created_by, created_at FROM agent_versions
WHERE agent_id = $1 AND workspace_id = $2
ORDER BY version DESC
`

type ListAgentVersionsForWorkspaceParams struct {
	AgentID     uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) ListAgentVersionsForWorkspace(ctx context.Context, arg ListAgentVersionsForWorkspaceParams) ([]AgentVersion, error) {
	rows, err := q.db.Query(ctx, listAgentVersionsForWorkspace, arg.AgentID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentVersion{}
	for rows.Next() {
		var i AgentVersion
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.WorkspaceID,
			&i.Version,
			&i.Provider,
			&i.Model,
			&i.Capabilities,
			&i.ToolPolicy,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsForWorkspace = `-- name: ListAgentsForWorkspace :many
SELECT id, workspace_id, name, current_version_id, created_by, created_at, updated_at FROM agents
WHERE workspace_id = $1
ORDER BY name
`

func (q *Queries) ListAgentsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CurrentVersionID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentForUpdate = `-- name: LockAgentForUpdate :one
SELECT id, workspace_id, name, current_version_id, created_by, created_at, updated_at FROM agents
WHERE id = $1 AND workspace_id = $2
FOR UPDATE
`

type LockAgentForUpdateParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Taken before computing the next version number. Without it two concurrent
// edits both read the same MAX(version) and one fails on the unique index —
// an error the caller can do nothing useful with.
func (q *Queries) LockAgentForUpdate(ctx context.Context, arg LockAgentForUpdateParams) (Agent, error) {
	row := q.db.QueryRow(ctx, lockAgentForUpdate, arg.ID, arg.WorkspaceID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextAgentVersionNumber = `-- name: NextAgentVersionNumber :one
SELECT COALESCE(MAX(version), 0) + 1 AS next
FROM agent_versions
WHERE agent_id = $1 AND workspace_id = $2
`

type NextAgentVersionNumberParams struct {
	AgentID     uuid.UUID
	WorkspaceID uuid.UUID
}

// Read under the agent's row lock by the caller, so two concurrent edits
// cannot both compute the same next number and collide on the unique index.
func (q *Queries) NextAgentVersionNumber(ctx context.Context, arg NextAgentVersionNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextAgentVersionNumber, arg.AgentID, arg.WorkspaceID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const renameAgent = `-- name: RenameAgent :one
UPDATE agents
SET name = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, current_version_id, created_by, created_at, updated_at
`

type RenameAgentParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
}

func (q *Queries) RenameAgent(ctx context.Context, arg RenameAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, renameAgent, arg.ID, arg.WorkspaceID, arg.Name)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAgentCurrentVersion = `-- name: SetAgentCurrentVersion :one
UPDATE agents
SET current_version_id = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, current_version_id, created_by, created_at, updated_at
`

type SetAgentCurrentVersionParams struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	CurrentVersionID pgtype.UUID
}

// The pointer is the only mutable thing about a profile. Moving it changes
// what the next session will use and nothing about what past sessions did.
func (q *Queries) SetAgentCurrentVersion(ctx context.Context, arg SetAgentCurrentVersionParams) (Agent, error) {
	row := q.db.QueryRow(ctx, setAgentCurrentVersion, arg.ID, arg.WorkspaceID, arg.CurrentVersionID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
