// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: egress.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
)

const countWorkspaceEgressHosts = `-- name: CountWorkspaceEgressHosts :one
SELECT count(*) FROM workspace_egress_hosts WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceEgressHosts(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceEgressHosts, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteWorkspaceEgressHost = `-- name: DeleteWorkspaceEgressHost :one
DELETE FROM workspace_egress_hosts WHERE id = $1 AND workspace_id = $2 RETURNING id, workspace_id, hostname, created_by, created_at
`

type DeleteWorkspaceEgressHostParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteWorkspaceEgressHost(ctx context.Context, arg DeleteWorkspaceEgressHostParams) (WorkspaceEgressHost, error) {
	row := q.db.QueryRow(ctx, deleteWorkspaceEgressHost, arg.ID, arg.WorkspaceID)
	var i WorkspaceEgressHost
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRunnerEgressSnapshot = `-- name: GetRunnerEgressSnapshot :one
SELECT runner_id, workspace_id, session_id, hosts, created_at FROM runner_egress_snapshots WHERE runner_id = $1 AND workspace_id = $2
`

type GetRunnerEgressSnapshotParams struct {
	RunnerID    uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetRunnerEgressSnapshot(ctx context.Context, arg GetRunnerEgressSnapshotParams) (RunnerEgressSnapshot, error) {
	row := q.db.QueryRow(ctx, getRunnerEgressSnapshot, arg.RunnerID, arg.WorkspaceID)
	var i RunnerEgressSnapshot
	err := row.Scan(
		&i.RunnerID,
		&i.WorkspaceID,
		&i.SessionID,
		&i.Hosts,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceEgressHost = `-- name: GetWorkspaceEgressHost :one
SELECT id, workspace_id, hostname, created_by, created_at FROM workspace_egress_hosts WHERE id = $1 AND workspace_id = $2
`

type GetWorkspaceEgressHostParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetWorkspaceEgressHost(ctx context.Context, arg GetWorkspaceEgressHostParams) (WorkspaceEgressHost, error) {
	row := q.db.QueryRow(ctx, getWorkspaceEgressHost, arg.ID, arg.WorkspaceID)
	var i WorkspaceEgressHost
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorkspaceEgressHost = `-- name: InsertWorkspaceEgressHost :one
INSERT INTO workspace_egress_hosts (id, workspace_id, hostname, created_by)
VALUES ($1, $2, $3, $4) RETURNING id, workspace_id, hostname, created_by, created_at
`

type InsertWorkspaceEgressHostParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Hostname    string
	CreatedBy   uuid.UUID
}

func (q *Queries) InsertWorkspaceEgressHost(ctx context.Context, arg InsertWorkspaceEgressHostParams) (WorkspaceEgressHost, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceEgressHost,
		arg.ID,
		arg.WorkspaceID,
		arg.Hostname,
		arg.CreatedBy,
	)
	var i WorkspaceEgressHost
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspaceEgressHosts = `-- name: ListWorkspaceEgressHosts :many
SELECT id, workspace_id, hostname, created_by, created_at FROM workspace_egress_hosts WHERE workspace_id = $1 ORDER BY hostname
`

func (q *Queries) ListWorkspaceEgressHosts(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceEgressHost, error) {
	rows, err := q.db.Query(ctx, listWorkspaceEgressHosts, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceEgressHost{}
	for rows.Next() {
		var i WorkspaceEgressHost
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Hostname,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workspaceEgressHostExists = `-- name: WorkspaceEgressHostExists :one
SELECT EXISTS (SELECT 1 FROM workspace_egress_hosts WHERE workspace_id = $1 AND hostname = $2)
`

type WorkspaceEgressHostExistsParams struct {
	WorkspaceID uuid.UUID
	Hostname    string
}

func (q *Queries) WorkspaceEgressHostExists(ctx context.Context, arg WorkspaceEgressHostExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceEgressHostExists, arg.WorkspaceID, arg.Hostname)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
