// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendSessionEvent = `-- name: AppendSessionEvent :one
INSERT INTO session_events (
    session_id, sequence, workspace_id, runner_id, event_id, type,
    schema_version, correlation_id, occurred_at, received_at, payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT ON CONSTRAINT session_events_dedup_key DO NOTHING
RETURNING sequence
`

type AppendSessionEventParams struct {
	SessionID     uuid.UUID
	Sequence      int64
	WorkspaceID   uuid.UUID
	RunnerID      uuid.UUID
	EventID       uuid.UUID
	Type          string
	SchemaVersion string
	CorrelationID uuid.UUID
	OccurredAt    pgtype.Timestamptz
	ReceivedAt    pgtype.Timestamptz
	Payload       []byte
}

// DO NOTHING on the deduplication key, so a duplicate returns no row rather
// than an error — the caller distinguishes it without parsing a message.
func (q *Queries) AppendSessionEvent(ctx context.Context, arg AppendSessionEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, appendSessionEvent,
		arg.SessionID,
		arg.Sequence,
		arg.WorkspaceID,
		arg.RunnerID,
		arg.EventID,
		arg.Type,
		arg.SchemaVersion,
		arg.CorrelationID,
		arg.OccurredAt,
		arg.ReceivedAt,
		arg.Payload,
	)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const listSessionEvents = `-- name: ListSessionEvents :many
SELECT session_id, sequence, workspace_id, runner_id, event_id, type, schema_version, correlation_id, occurred_at, received_at, payload FROM session_events
WHERE session_id = $1 AND workspace_id = $2
ORDER BY sequence
`

type ListSessionEventsParams struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
}

// For tests and, later, the session room. Scoped by workspace as well as the
// policy, and ordered by the sequence — never by occurred_at, which is a claim.
func (q *Queries) ListSessionEvents(ctx context.Context, arg ListSessionEventsParams) ([]SessionEvent, error) {
	rows, err := q.db.Query(ctx, listSessionEvents, arg.SessionID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.SessionID,
			&i.Sequence,
			&i.WorkspaceID,
			&i.RunnerID,
			&i.EventID,
			&i.Type,
			&i.SchemaVersion,
			&i.CorrelationID,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSessionForEvent = `-- name: LockSessionForEvent :one
SELECT state FROM sessions
WHERE id = $1 AND workspace_id = $2
FOR SHARE
`

type LockSessionForEventParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// The session's state, read under a share lock inside the append transaction.
//
// A transition takes FOR UPDATE on this row, so the two serialise: an event
// cannot be appended between a session's terminal transition and its commit,
// and a terminal transition cannot slip in between this read and the
// event's insert. Reading the state earlier, outside this transaction, is
// the race that let a terminal session gain an event.
func (q *Queries) LockSessionForEvent(ctx context.Context, arg LockSessionForEventParams) (string, error) {
	row := q.db.QueryRow(ctx, lockSessionForEvent, arg.ID, arg.WorkspaceID)
	var state string
	err := row.Scan(&state)
	return state, err
}

const nextSessionEventSequence = `-- name: NextSessionEventSequence :one
INSERT INTO session_event_sequences (session_id, workspace_id, last_sequence)
VALUES ($1, $2, 1)
ON CONFLICT (session_id) DO UPDATE
    SET last_sequence = session_event_sequences.last_sequence + 1
RETURNING last_sequence
`

type NextSessionEventSequenceParams struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
}

// Takes the next number for a session, creating its counter on first use.
//
// The upsert locks the counter row until the transaction ends, which is what
// serialises two ingestor replicas on one session. If the insert that follows
// is a duplicate, the caller rolls back, and the number goes with it.
func (q *Queries) NextSessionEventSequence(ctx context.Context, arg NextSessionEventSequenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextSessionEventSequence, arg.SessionID, arg.WorkspaceID)
	var last_sequence int64
	err := row.Scan(&last_sequence)
	return last_sequence, err
}

const quarantineSessionEvent = `-- name: QuarantineSessionEvent :exec
INSERT INTO session_event_quarantine (
    subject, reason, event_id, session_id, workspace_id, schema_version,
    size_bytes, delivery_count, payload_sha256
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type QuarantineSessionEventParams struct {
	Subject       string
	Reason        string
	EventID       pgtype.UUID
	SessionID     pgtype.UUID
	WorkspaceID   pgtype.UUID
	SchemaVersion *string
	SizeBytes     int32
	DeliveryCount int32
	PayloadSha256 string
}

func (q *Queries) QuarantineSessionEvent(ctx context.Context, arg QuarantineSessionEventParams) error {
	_, err := q.db.Exec(ctx, quarantineSessionEvent,
		arg.Subject,
		arg.Reason,
		arg.EventID,
		arg.SessionID,
		arg.WorkspaceID,
		arg.SchemaVersion,
		arg.SizeBytes,
		arg.DeliveryCount,
		arg.PayloadSha256,
	)
	return err
}

const sessionEventExists = `-- name: SessionEventExists :one
SELECT EXISTS (
    SELECT 1 FROM session_events
    WHERE session_id = $1 AND runner_id = $2 AND event_id = $3
)
`

type SessionEventExistsParams struct {
	SessionID uuid.UUID
	RunnerID  uuid.UUID
	EventID   uuid.UUID
}

// Whether an event is already stored, for a terminal session: a redelivery of
// an event stored before the session ended is a duplicate, not a refusal.
func (q *Queries) SessionEventExists(ctx context.Context, arg SessionEventExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionEventExists, arg.SessionID, arg.RunnerID, arg.EventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
