// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendSessionEvent = `-- name: AppendSessionEvent :one
INSERT INTO session_events (
    session_id, sequence, workspace_id, runner_id, event_id, type,
    schema_version, correlation_id, occurred_at, received_at, payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT ON CONSTRAINT session_events_dedup_key DO NOTHING
RETURNING sequence
`

type AppendSessionEventParams struct {
	SessionID     uuid.UUID
	Sequence      int64
	WorkspaceID   uuid.UUID
	RunnerID      uuid.UUID
	EventID       uuid.UUID
	Type          string
	SchemaVersion string
	CorrelationID uuid.UUID
	OccurredAt    pgtype.Timestamptz
	ReceivedAt    pgtype.Timestamptz
	Payload       []byte
}

// DO NOTHING on the deduplication key, so a duplicate returns no row rather
// than an error — the caller distinguishes it without parsing a message.
func (q *Queries) AppendSessionEvent(ctx context.Context, arg AppendSessionEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, appendSessionEvent,
		arg.SessionID,
		arg.Sequence,
		arg.WorkspaceID,
		arg.RunnerID,
		arg.EventID,
		arg.Type,
		arg.SchemaVersion,
		arg.CorrelationID,
		arg.OccurredAt,
		arg.ReceivedAt,
		arg.Payload,
	)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const listSessionEvents = `-- name: ListSessionEvents :many
SELECT session_id, sequence, workspace_id, runner_id, event_id, type, schema_version, correlation_id, occurred_at, received_at, payload FROM session_events
WHERE session_id = $1 AND workspace_id = $2
ORDER BY sequence
`

type ListSessionEventsParams struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
}

// For tests and, later, the session room. Scoped by workspace as well as the
// policy, and ordered by the sequence — never by occurred_at, which is a claim.
func (q *Queries) ListSessionEvents(ctx context.Context, arg ListSessionEventsParams) ([]SessionEvent, error) {
	rows, err := q.db.Query(ctx, listSessionEvents, arg.SessionID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionEvent{}
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.SessionID,
			&i.Sequence,
			&i.WorkspaceID,
			&i.RunnerID,
			&i.EventID,
			&i.Type,
			&i.SchemaVersion,
			&i.CorrelationID,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSessionEventSequence = `-- name: LockSessionEventSequence :exec
INSERT INTO session_event_sequences (session_id, workspace_id, last_sequence)
VALUES ($1, $2, 0)
ON CONFLICT (session_id) DO UPDATE
    SET last_sequence = session_event_sequences.last_sequence
`

type LockSessionEventSequenceParams struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
}

// Taken by a transition into a terminal state, before it writes the state.
//
// Creates the counter if the session has emitted nothing yet, so the lock
// always has a row to take. Exclusive, like every append's increment, so the
// two queue fairly: a terminal transition waits for at most the appends
// already holding or queued for the row, never for an unbounded stream.
func (q *Queries) LockSessionEventSequence(ctx context.Context, arg LockSessionEventSequenceParams) error {
	_, err := q.db.Exec(ctx, lockSessionEventSequence, arg.SessionID, arg.WorkspaceID)
	return err
}

const nextSessionEventSequence = `-- name: NextSessionEventSequence :one
INSERT INTO session_event_sequences (session_id, workspace_id, last_sequence)
VALUES ($1, $2, 1)
ON CONFLICT (session_id) DO UPDATE
    SET last_sequence = session_event_sequences.last_sequence + 1
RETURNING last_sequence
`

type NextSessionEventSequenceParams struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
}

// Takes the next number for a session, creating its counter on first use.
//
// The upsert locks the counter row until the transaction ends, which is what
// serialises two ingestor replicas on one session. If the insert that follows
// is a duplicate, the caller rolls back, and the number goes with it.
func (q *Queries) NextSessionEventSequence(ctx context.Context, arg NextSessionEventSequenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextSessionEventSequence, arg.SessionID, arg.WorkspaceID)
	var last_sequence int64
	err := row.Scan(&last_sequence)
	return last_sequence, err
}

const quarantineSessionEvent = `-- name: QuarantineSessionEvent :exec
INSERT INTO session_event_quarantine (
    subject, reason, event_id, session_id, workspace_id, schema_version,
    size_bytes, delivery_count, payload_sha256
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type QuarantineSessionEventParams struct {
	Subject       string
	Reason        string
	EventID       pgtype.UUID
	SessionID     pgtype.UUID
	WorkspaceID   pgtype.UUID
	SchemaVersion *string
	SizeBytes     int32
	DeliveryCount int32
	PayloadSha256 string
}

func (q *Queries) QuarantineSessionEvent(ctx context.Context, arg QuarantineSessionEventParams) error {
	_, err := q.db.Exec(ctx, quarantineSessionEvent,
		arg.Subject,
		arg.Reason,
		arg.EventID,
		arg.SessionID,
		arg.WorkspaceID,
		arg.SchemaVersion,
		arg.SizeBytes,
		arg.DeliveryCount,
		arg.PayloadSha256,
	)
	return err
}

const sessionEventExists = `-- name: SessionEventExists :one
SELECT EXISTS (
    SELECT 1 FROM session_events
    WHERE session_id = $1 AND runner_id = $2 AND event_id = $3
)
`

type SessionEventExistsParams struct {
	SessionID uuid.UUID
	RunnerID  uuid.UUID
	EventID   uuid.UUID
}

// Whether an event is already stored, for a terminal session: a redelivery of
// an event stored before the session ended is a duplicate, not a refusal.
func (q *Queries) SessionEventExists(ctx context.Context, arg SessionEventExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionEventExists, arg.SessionID, arg.RunnerID, arg.EventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const sessionProviderFailure = `-- name: SessionProviderFailure :one
SELECT (payload->>'code')::text AS code
FROM session_events
WHERE session_id = $1 AND workspace_id = $2 AND type = 'provider.failed'
ORDER BY sequence
LIMIT 1
`

type SessionProviderFailureParams struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
}

// The first provider.failed a session's history holds, if any. Read after the
// drain, so the history is complete. The code is a validated stable identifier
// (domain.DecodeEvent); the provider's message text is never read here.
func (q *Queries) SessionProviderFailure(ctx context.Context, arg SessionProviderFailureParams) (string, error) {
	row := q.db.QueryRow(ctx, sessionProviderFailure, arg.SessionID, arg.WorkspaceID)
	var code string
	err := row.Scan(&code)
	return code, err
}

const sessionStateForEvent = `-- name: SessionStateForEvent :one
SELECT state FROM sessions
WHERE id = $1 AND workspace_id = $2
`

type SessionStateForEventParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// The session's state, read inside the append transaction **after** the
// counter row is locked — never under a lock on the session row itself.
//
// An earlier revision took FOR SHARE on the session here. Measured under
// continuous output, it starved transitions: new share lockers kept jumping a
// waiting FOR UPDATE, and a terminal transition waited the whole three-second
// run. The counter row is the serialisation point instead (see
// LockSessionEventSequence): a terminal transition locks it too, so either
// the transition commits first and this read — a fresh snapshot, since the
// lock was taken by an earlier statement — sees it, or the append commits
// first and the transition waits for exactly that one append.
func (q *Queries) SessionStateForEvent(ctx context.Context, arg SessionStateForEventParams) (string, error) {
	row := q.db.QueryRow(ctx, sessionStateForEvent, arg.ID, arg.WorkspaceID)
	var state string
	err := row.Scan(&state)
	return state, err
}
