// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearInstallationPermissions = `-- name: ClearInstallationPermissions :exec
DELETE FROM repository_permissions
WHERE installation_id = $1 AND workspace_id = $2
`

type ClearInstallationPermissionsParams struct {
	InstallationID uuid.UUID
	WorkspaceID    uuid.UUID
}

func (q *Queries) ClearInstallationPermissions(ctx context.Context, arg ClearInstallationPermissionsParams) error {
	_, err := q.db.Exec(ctx, clearInstallationPermissions, arg.InstallationID, arg.WorkspaceID)
	return err
}

const connectInstallation = `-- name: ConnectInstallation :one
INSERT INTO github_installations (
    id, workspace_id, github_installation_id, account_login, account_type,
    repository_selection, connected_by
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, github_installation_id, account_login, account_type, repository_selection, connected_by, suspended_at, deleted_at, created_at, updated_at
`

type ConnectInstallationParams struct {
	ID                   uuid.UUID
	WorkspaceID          uuid.UUID
	GithubInstallationID int64
	AccountLogin         string
	AccountType          string
	RepositorySelection  string
	ConnectedBy          uuid.UUID
}

// Bind an installation to a workspace.
//
// No ON CONFLICT clause on purpose. The unique index on
// github_installation_id is what refuses a second binding, and the refusal
// must reach the caller as an error rather than be absorbed into an update:
// quietly rebinding would move a repository grant between tenants.
func (q *Queries) ConnectInstallation(ctx context.Context, arg ConnectInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, connectInstallation,
		arg.ID,
		arg.WorkspaceID,
		arg.GithubInstallationID,
		arg.AccountLogin,
		arg.AccountType,
		arg.RepositorySelection,
		arg.ConnectedBy,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GithubInstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.ConnectedBy,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallationByGitHubIDForWorkspace = `-- name: GetInstallationByGitHubIDForWorkspace :one
SELECT id, workspace_id, github_installation_id, account_login, account_type, repository_selection, connected_by, suspended_at, deleted_at, created_at, updated_at FROM github_installations
WHERE github_installation_id = $1 AND workspace_id = $2
`

type GetInstallationByGitHubIDForWorkspaceParams struct {
	GithubInstallationID int64
	WorkspaceID          uuid.UUID
}

func (q *Queries) GetInstallationByGitHubIDForWorkspace(ctx context.Context, arg GetInstallationByGitHubIDForWorkspaceParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallationByGitHubIDForWorkspace, arg.GithubInstallationID, arg.WorkspaceID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GithubInstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.ConnectedBy,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallationForWorkspace = `-- name: GetInstallationForWorkspace :one
SELECT id, workspace_id, github_installation_id, account_login, account_type, repository_selection, connected_by, suspended_at, deleted_at, created_at, updated_at FROM github_installations
WHERE id = $1 AND workspace_id = $2
`

type GetInstallationForWorkspaceParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Scoped by workspace, so an installation id from one tenant cannot be read
// through another even before the policies are consulted.
func (q *Queries) GetInstallationForWorkspace(ctx context.Context, arg GetInstallationForWorkspaceParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallationForWorkspace, arg.ID, arg.WorkspaceID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GithubInstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.ConnectedBy,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryForWorkspace = `-- name: GetRepositoryForWorkspace :one
SELECT id, workspace_id, installation_id, github_repository_id, owner, name, default_branch, private, granted, created_at, updated_at FROM repositories
WHERE id = $1 AND workspace_id = $2
`

type GetRepositoryForWorkspaceParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetRepositoryForWorkspace(ctx context.Context, arg GetRepositoryForWorkspaceParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryForWorkspace, arg.ID, arg.WorkspaceID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InstallationID,
		&i.GithubRepositoryID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.Private,
		&i.Granted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveInstallationsForWorkspace = `-- name: ListActiveInstallationsForWorkspace :many
SELECT id, workspace_id, github_installation_id, account_login, account_type, repository_selection, connected_by, suspended_at, deleted_at, created_at, updated_at FROM github_installations
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

// What the workspace currently has connected. Removed installations are kept
// for their repository history but are not connections any more.
func (q *Queries) ListActiveInstallationsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]GithubInstallation, error) {
	rows, err := q.db.Query(ctx, listActiveInstallationsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubInstallation{}
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.GithubInstallationID,
			&i.AccountLogin,
			&i.AccountType,
			&i.RepositorySelection,
			&i.ConnectedBy,
			&i.SuspendedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallationPermissions = `-- name: ListInstallationPermissions :many
SELECT installation_id, workspace_id, permission, access, recorded_at FROM repository_permissions
WHERE installation_id = $1 AND workspace_id = $2
ORDER BY permission
`

type ListInstallationPermissionsParams struct {
	InstallationID uuid.UUID
	WorkspaceID    uuid.UUID
}

func (q *Queries) ListInstallationPermissions(ctx context.Context, arg ListInstallationPermissionsParams) ([]RepositoryPermission, error) {
	rows, err := q.db.Query(ctx, listInstallationPermissions, arg.InstallationID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepositoryPermission{}
	for rows.Next() {
		var i RepositoryPermission
		if err := rows.Scan(
			&i.InstallationID,
			&i.WorkspaceID,
			&i.Permission,
			&i.Access,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesForWorkspace = `-- name: ListRepositoriesForWorkspace :many
SELECT id, workspace_id, installation_id, github_repository_id, owner, name, default_branch, private, granted, created_at, updated_at FROM repositories
WHERE workspace_id = $1
ORDER BY owner, name
`

// Withdrawn repositories are returned too, with granted = false, so the
// interface can say "access was removed" rather than silently dropping a
// repository someone was using yesterday.
func (q *Queries) ListRepositoriesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InstallationID,
			&i.GithubRepositoryID,
			&i.Owner,
			&i.Name,
			&i.DefaultBranch,
			&i.Private,
			&i.Granted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstallationDeleted = `-- name: MarkInstallationDeleted :exec
UPDATE github_installations
SET deleted_at = now(), suspended_at = COALESCE(suspended_at, now()), updated_at = now()
WHERE id = $1 AND workspace_id = $2
`

type MarkInstallationDeletedParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Used when GitHub reports the installation removed.
//
// The row is marked, not deleted. Deleting it cascades to the repositories,
// and those rows are the record that access once existed — which is what makes
// an old audit entry or a finished session readable. Withdrawing the
// repositories is a separate statement in the same transaction.
func (q *Queries) MarkInstallationDeleted(ctx context.Context, arg MarkInstallationDeletedParams) error {
	_, err := q.db.Exec(ctx, markInstallationDeleted, arg.ID, arg.WorkspaceID)
	return err
}

const pruneWebhookDeliveries = `-- name: PruneWebhookDeliveries :exec
DELETE FROM github_webhook_deliveries
WHERE received_at < now() - $1::interval
`

// Deliveries are only needed while deduplication might see a retry. GitHub
// gives up well inside this window.
func (q *Queries) PruneWebhookDeliveries(ctx context.Context, retention pgtype.Interval) error {
	_, err := q.db.Exec(ctx, pruneWebhookDeliveries, retention)
	return err
}

const recordInstallationPermission = `-- name: RecordInstallationPermission :exec
INSERT INTO repository_permissions (installation_id, workspace_id, permission, access)
VALUES ($1, $2, $3, $4)
ON CONFLICT (installation_id, permission) DO UPDATE
SET access = EXCLUDED.access, recorded_at = now()
`

type RecordInstallationPermissionParams struct {
	InstallationID uuid.UUID
	WorkspaceID    uuid.UUID
	Permission     string
	Access         string
}

func (q *Queries) RecordInstallationPermission(ctx context.Context, arg RecordInstallationPermissionParams) error {
	_, err := q.db.Exec(ctx, recordInstallationPermission,
		arg.InstallationID,
		arg.WorkspaceID,
		arg.Permission,
		arg.Access,
	)
	return err
}

const recordWebhookDelivery = `-- name: RecordWebhookDelivery :one
INSERT INTO github_webhook_deliveries (delivery_id, event, action)
VALUES ($1, $2, $3)
ON CONFLICT (delivery_id) DO NOTHING
RETURNING delivery_id, event, action, received_at
`

type RecordWebhookDeliveryParams struct {
	DeliveryID string
	Event      string
	Action     *string
}

// Deduplication. GitHub retries deliveries, and a retry must not produce a
// second effect.
//
// ON CONFLICT DO NOTHING with a RETURNING clause yields no row when the
// delivery has been seen, which is how the caller distinguishes the two
// without a separate read and the race that would come with it.
func (q *Queries) RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) (GithubWebhookDelivery, error) {
	row := q.db.QueryRow(ctx, recordWebhookDelivery, arg.DeliveryID, arg.Event, arg.Action)
	var i GithubWebhookDelivery
	err := row.Scan(
		&i.DeliveryID,
		&i.Event,
		&i.Action,
		&i.ReceivedAt,
	)
	return i, err
}

const setInstallationSelection = `-- name: SetInstallationSelection :one
UPDATE github_installations
SET repository_selection = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, github_installation_id, account_login, account_type, repository_selection, connected_by, suspended_at, deleted_at, created_at, updated_at
`

type SetInstallationSelectionParams struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	RepositorySelection string
}

func (q *Queries) SetInstallationSelection(ctx context.Context, arg SetInstallationSelectionParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, setInstallationSelection, arg.ID, arg.WorkspaceID, arg.RepositorySelection)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GithubInstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.ConnectedBy,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setInstallationSuspended = `-- name: SetInstallationSuspended :one
UPDATE github_installations
SET suspended_at = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, github_installation_id, account_login, account_type, repository_selection, connected_by, suspended_at, deleted_at, created_at, updated_at
`

type SetInstallationSuspendedParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	SuspendedAt pgtype.Timestamptz
}

// Suspension is recorded, never deleted. Unsuspending must restore the
// previous state rather than require a fresh install, and keeping the rows is
// what makes that possible.
func (q *Queries) SetInstallationSuspended(ctx context.Context, arg SetInstallationSuspendedParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, setInstallationSuspended, arg.ID, arg.WorkspaceID, arg.SuspendedAt)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GithubInstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.ConnectedBy,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepository = `-- name: UpsertRepository :one
INSERT INTO repositories (
    id, workspace_id, installation_id, github_repository_id,
    owner, name, default_branch, private, granted
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, true)
ON CONFLICT (installation_id, github_repository_id) DO UPDATE
SET owner          = EXCLUDED.owner,
    name           = EXCLUDED.name,
    default_branch = EXCLUDED.default_branch,
    private        = EXCLUDED.private,
    granted        = true,
    updated_at     = now()
RETURNING id, workspace_id, installation_id, github_repository_id, owner, name, default_branch, private, granted, created_at, updated_at
`

type UpsertRepositoryParams struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	InstallationID     uuid.UUID
	GithubRepositoryID int64
	Owner              string
	Name               string
	DefaultBranch      string
	Private            bool
}

// Reconciliation writes every repository GitHub currently grants.
//
// ON CONFLICT updates rather than inserts because a repository seen before may
// have been renamed, transferred, made private, or re-granted after being
// withdrawn. The conflict target is (installation_id, github_repository_id):
// the GitHub id is the identity, and owner/name are mutable descriptions of it.
func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, upsertRepository,
		arg.ID,
		arg.WorkspaceID,
		arg.InstallationID,
		arg.GithubRepositoryID,
		arg.Owner,
		arg.Name,
		arg.DefaultBranch,
		arg.Private,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InstallationID,
		&i.GithubRepositoryID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.Private,
		&i.Granted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const withdrawAllRepositories = `-- name: WithdrawAllRepositories :exec
UPDATE repositories
SET granted = false, updated_at = now()
WHERE installation_id = $1 AND workspace_id = $2 AND granted = true
`

type WithdrawAllRepositoriesParams struct {
	InstallationID uuid.UUID
	WorkspaceID    uuid.UUID
}

func (q *Queries) WithdrawAllRepositories(ctx context.Context, arg WithdrawAllRepositoriesParams) error {
	_, err := q.db.Exec(ctx, withdrawAllRepositories, arg.InstallationID, arg.WorkspaceID)
	return err
}

const withdrawRepositoriesNotIn = `-- name: WithdrawRepositoriesNotIn :exec
UPDATE repositories
SET granted = false, updated_at = now()
WHERE installation_id = $1
  AND workspace_id = $2
  AND granted = true
  AND NOT (github_repository_id = ANY($3::bigint[]))
`

type WithdrawRepositoriesNotInParams struct {
	InstallationID uuid.UUID
	WorkspaceID    uuid.UUID
	GrantedIds     []int64
}

// Mark everything the installation no longer grants.
//
// Rows are withdrawn rather than deleted: the record that access once existed
// is what makes an old audit entry or session readable later. Passing the
// currently granted set and negating it, rather than deleting named ones,
// means a repository that vanished without an event is still caught.
func (q *Queries) WithdrawRepositoriesNotIn(ctx context.Context, arg WithdrawRepositoriesNotInParams) error {
	_, err := q.db.Exec(ctx, withdrawRepositoriesNotIn, arg.InstallationID, arg.WorkspaceID, arg.GrantedIds)
	return err
}
