// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO idempotency_keys (
    id, workspace_id, user_id, endpoint, idempotency_key,
    request_fingerprint, leased_until
)
VALUES ($1, $2, $3, $4, $5, $6, now() + $7::interval)
ON CONFLICT (workspace_id, user_id, endpoint, idempotency_key) DO UPDATE
SET leased_until         = now() + $7::interval,
    request_fingerprint  = EXCLUDED.request_fingerprint,
    created_at           = now()
WHERE idempotency_keys.completed_at IS NULL
  AND idempotency_keys.leased_until < now()
RETURNING id, workspace_id, user_id, endpoint, idempotency_key, request_fingerprint, response_status, response_body, origin_request_id, leased_until, created_at, completed_at
`

type ClaimIdempotencyKeyParams struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	UserID             uuid.UUID
	Endpoint           string
	IdempotencyKey     string
	RequestFingerprint []byte
	Lease              pgtype.Interval
}

// The claim, as one statement rather than a check followed by an insert.
//
// ON CONFLICT DO UPDATE rather than DO NOTHING, because the conflict has two
// meanings and only the update can tell them apart while taking the lease: a
// row whose lease has expired and which never completed is a claim whose
// holder died, and it is claimable again; anything else is either in flight or
// complete and must not be disturbed.
//
// The WHERE on the update is what makes that safe. When it does not match,
// nothing is written and nothing is returned, and the caller reads the row to
// find out which of the two it is.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Endpoint,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.Lease,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Endpoint,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.OriginRequestID,
		&i.LeasedUntil,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET response_status   = $5,
    response_body     = $6,
    origin_request_id = $7,
    completed_at      = now(),
    leased_until      = NULL
WHERE workspace_id = $1 AND user_id = $2 AND endpoint = $3 AND idempotency_key = $4
`

type CompleteIdempotencyKeyParams struct {
	WorkspaceID     uuid.UUID
	UserID          uuid.UUID
	Endpoint        string
	IdempotencyKey  string
	ResponseStatus  *int32
	ResponseBody    []byte
	OriginRequestID *string
}

// Written in the same transaction as the work it describes. A response
// recorded afterwards could fail while the work stood, and the expiring lease
// would then let a retry do the work a second time.
func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.WorkspaceID,
		arg.UserID,
		arg.Endpoint,
		arg.IdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.OriginRequestID,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, workspace_id, user_id, endpoint, idempotency_key, request_fingerprint, response_status, response_body, origin_request_id, leased_until, created_at, completed_at FROM idempotency_keys
WHERE workspace_id = $1 AND user_id = $2 AND endpoint = $3 AND idempotency_key = $4
`

type GetIdempotencyKeyParams struct {
	WorkspaceID    uuid.UUID
	UserID         uuid.UUID
	Endpoint       string
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey,
		arg.WorkspaceID,
		arg.UserID,
		arg.Endpoint,
		arg.IdempotencyKey,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Endpoint,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.OriginRequestID,
		&i.LeasedUntil,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const pruneIdempotencyKeys = `-- name: PruneIdempotencyKeys :execrows
DELETE FROM idempotency_keys
WHERE created_at < now() - $1::interval
`

// Retention. A retry is recovery from a lost response, which happens inside a
// request-timeout window rather than days later — and these rows store a
// response body carrying identifiers, so they are customer data and shorter is
// better.
func (q *Queries) PruneIdempotencyKeys(ctx context.Context, retention pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, pruneIdempotencyKeys, retention)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE workspace_id = $1 AND user_id = $2 AND endpoint = $3 AND idempotency_key = $4
  AND completed_at IS NULL
`

type ReleaseIdempotencyKeyParams struct {
	WorkspaceID    uuid.UUID
	UserID         uuid.UUID
	Endpoint       string
	IdempotencyKey string
}

// The work failed, so the key is released at once rather than making a
// legitimate retry wait out the lease. Guarded on not being complete, so a
// late release cannot erase a finished record.
func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey,
		arg.WorkspaceID,
		arg.UserID,
		arg.Endpoint,
		arg.IdempotencyKey,
	)
	return err
}
