// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimInvitation = `-- name: ClaimInvitation :one
UPDATE workspace_invitations
SET accepted_at = now(), accepted_by = $2
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, workspace_id, email, role, token_hash, invited_by, expires_at, created_at, accepted_at, accepted_by, revoked_at, revoked_by
`

type ClaimInvitationParams struct {
	ID         uuid.UUID
	AcceptedBy pgtype.UUID
}

// Single-statement claim: the WHERE clause is what makes the token single
// use. Two concurrent accepts race here and exactly one matches a row, so no
// lock is needed and no second membership can be created.
func (q *Queries) ClaimInvitation(ctx context.Context, arg ClaimInvitationParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, claimInvitation, arg.ID, arg.AcceptedBy)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO workspace_invitations (id, workspace_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, email, role, token_hash, invited_by, expires_at, created_at, accepted_at, accepted_by, revoked_at, revoked_by
`

type CreateInvitationParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       string
	Role        string
	TokenHash   []byte
	InvitedBy   uuid.UUID
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, created_at, accepted_at, accepted_by, revoked_at, revoked_by FROM weave_invitation_by_token($1)
`

// Deliberately unscoped by workspace: the token is the only thing the
// acceptor holds, and they are not yet a member of anything. The caller
// checks status and email before acting on the result.
//
// Goes through weave_invitation_by_token rather than the table, because
// row-level security would otherwise match no row — there is no workspace
// context to match against. The function is SECURITY DEFINER and returns only
// the row whose hash was presented.
func (q *Queries) GetInvitationByTokenHash(ctx context.Context, presentedHash []byte) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, presentedHash)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const getInvitationForWorkspace = `-- name: GetInvitationForWorkspace :one
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, created_at, accepted_at, accepted_by, revoked_at, revoked_by FROM workspace_invitations
WHERE id = $1 AND workspace_id = $2
`

type GetInvitationForWorkspaceParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Scoped by workspace so an invitation id from one tenant cannot be revoked
// through another.
func (q *Queries) GetInvitationForWorkspace(ctx context.Context, arg GetInvitationForWorkspaceParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationForWorkspace, arg.ID, arg.WorkspaceID)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const getInvitationWorkspaceContext = `-- name: GetInvitationWorkspaceContext :one
SELECT w.name AS workspace_name,
       u.email AS invited_by_email,
       u.display_name AS invited_by_display_name
FROM workspace_invitations i
JOIN workspaces w ON w.id = i.workspace_id
JOIN users u ON u.id = i.invited_by
WHERE i.id = $1
`

type GetInvitationWorkspaceContextRow struct {
	WorkspaceName        string
	InvitedByEmail       string
	InvitedByDisplayName *string
}

// Backing for the preview: the workspace name and who invited you, and
// nothing else about either.
func (q *Queries) GetInvitationWorkspaceContext(ctx context.Context, id uuid.UUID) (GetInvitationWorkspaceContextRow, error) {
	row := q.db.QueryRow(ctx, getInvitationWorkspaceContext, id)
	var i GetInvitationWorkspaceContextRow
	err := row.Scan(&i.WorkspaceName, &i.InvitedByEmail, &i.InvitedByDisplayName)
	return i, err
}

const getOutstandingInvitationForEmail = `-- name: GetOutstandingInvitationForEmail :one
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, created_at, accepted_at, accepted_by, revoked_at, revoked_by FROM workspace_invitations
WHERE workspace_id = $1 AND email = $2
  AND accepted_at IS NULL AND revoked_at IS NULL
`

type GetOutstandingInvitationForEmailParams struct {
	WorkspaceID uuid.UUID
	Email       string
}

// The row occupying the one-outstanding slot, if any. May be expired: the
// unique index predicate cannot reference now(), so the caller decides.
func (q *Queries) GetOutstandingInvitationForEmail(ctx context.Context, arg GetOutstandingInvitationForEmailParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, getOutstandingInvitationForEmail, arg.WorkspaceID, arg.Email)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const listInvitationsForWorkspace = `-- name: ListInvitationsForWorkspace :many
SELECT i.id, i.workspace_id, i.email, i.role, i.token_hash, i.invited_by, i.expires_at, i.created_at, i.accepted_at, i.accepted_by, i.revoked_at, i.revoked_by, u.email AS invited_by_email, u.display_name AS invited_by_display_name
FROM workspace_invitations i
JOIN users u ON u.id = i.invited_by
WHERE i.workspace_id = $1
ORDER BY i.created_at DESC
`

type ListInvitationsForWorkspaceRow struct {
	ID                   uuid.UUID
	WorkspaceID          uuid.UUID
	Email                string
	Role                 string
	TokenHash            []byte
	InvitedBy            uuid.UUID
	ExpiresAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	AcceptedAt           pgtype.Timestamptz
	AcceptedBy           pgtype.UUID
	RevokedAt            pgtype.Timestamptz
	RevokedBy            pgtype.UUID
	InvitedByEmail       string
	InvitedByDisplayName *string
}

func (q *Queries) ListInvitationsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListInvitationsForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listInvitationsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsForWorkspaceRow{}
	for rows.Next() {
		var i ListInvitationsForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.InvitedByEmail,
			&i.InvitedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE workspace_invitations
SET revoked_at = now(), revoked_by = $3
WHERE id = $1 AND workspace_id = $2
  AND accepted_at IS NULL AND revoked_at IS NULL
RETURNING id, workspace_id, email, role, token_hash, invited_by, expires_at, created_at, accepted_at, accepted_by, revoked_at, revoked_by
`

type RevokeInvitationParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	RevokedBy   pgtype.UUID
}

// Only an outstanding invitation can be revoked; revoking an accepted or
// already-revoked one matches no row.
func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, arg.ID, arg.WorkspaceID, arg.RevokedBy)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}
