// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Agent identity and the pointer to the settings currently in use. Editable; the settings are not.
type Agent struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	Name             string
	CurrentVersionID pgtype.UUID
	CreatedBy        uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// Append-only. A session is pinned to a version, so editing one would rewrite what finished sessions claim to have done.
type AgentVersion struct {
	ID           uuid.UUID
	AgentID      uuid.UUID
	WorkspaceID  uuid.UUID
	Version      int32
	Provider     string
	Model        string
	Capabilities []string
	ToolPolicy   []byte
	CreatedBy    uuid.UUID
	CreatedAt    pgtype.Timestamptz
}

// Append-only security log. Deliberately has no foreign keys so records outlive what they describe.
type AuditEvent struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ActorUserID pgtype.UUID
	Action      string
	Target      *string
	Detail      []byte
	OccurredAt  pgtype.Timestamptz
}

type GithubInstallation struct {
	ID                   uuid.UUID
	WorkspaceID          uuid.UUID
	GithubInstallationID int64
	AccountLogin         string
	AccountType          string
	RepositorySelection  string
	ConnectedBy          uuid.UUID
	SuspendedAt          pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type GithubWebhookDelivery struct {
	DeliveryID  string
	Event       string
	Action      *string
	ReceivedAt  pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

// Makes a retried mutation safe. The claim commits before the work and carries a lease, because a claim inside the work's transaction cannot refuse a concurrent caller.
type IdempotencyKey struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	UserID             uuid.UUID
	Endpoint           string
	IdempotencyKey     string
	Claimant           uuid.UUID
	RequestFingerprint []byte
	ResponseStatus     *int32
	ResponseBody       []byte
	OriginRequestID    *string
	LeasedUntil        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
}

// The durable promise that something happens elsewhere, written in the transaction that caused it. The claim is a lease with an expiry, not a flag.
type OutboxEvent struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Topic       string
	SubjectID   uuid.UUID
	Payload     []byte
	Attempts    int32
	AvailableAt pgtype.Timestamptz
	LeasedUntil pgtype.Timestamptz
	LastError   *string
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	// Fencing token, reissued on every claim. A publisher whose lease expired must not be able to complete, retry or terminate the claim that replaced it.
	Claimant pgtype.UUID
	// Set when a row will never succeed. Distinct from completed_at, which would claim work that never happened.
	TerminatedAt pgtype.Timestamptz
}

type Repository struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	InstallationID     uuid.UUID
	GithubRepositoryID int64
	Owner              string
	Name               string
	DefaultBranch      string
	Private            bool
	Granted            bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type RepositoryPermission struct {
	InstallationID uuid.UUID
	WorkspaceID    uuid.UUID
	Permission     string
	Access         string
	RecordedAt     pgtype.Timestamptz
}

// A run of an agent against a task. Carries the pinned agent version, which is the policy snapshot, and the branch intent M5 acts on.
type Session struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	TaskID         uuid.UUID
	AgentVersionID uuid.UUID
	State          string
	Version        int32
	RepositoryID   uuid.UUID
	BranchName     string
	BaseBranch     string
	ContinuesID    pgtype.UUID
	CreatedBy      uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	// The commit the session branch pointed at when the workflow confirmed it. NULL until then; written once.
	BranchSha *string
}

// Who is in a session and in what capacity. Distinct from workspace membership.
type SessionParticipant struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Capacity    string
	CreatedAt   pgtype.Timestamptz
}

// Append-only. Invariant 9: session history is append-only and ordered, so a correction is a new row.
type SessionStateTransition struct {
	ID              uuid.UUID
	SessionID       uuid.UUID
	WorkspaceID     uuid.UUID
	PreviousState   *string
	NextState       string
	ObservedVersion int32
	Reason          string
	ActorUserID     pgtype.UUID
	CreatedAt       pgtype.Timestamptz
}

// A unit of work someone wants done. The body is untrusted input: stored and returned as data, never interpolated.
type Task struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	RepositoryID pgtype.UUID
	Title        string
	Body         string
	Status       string
	CreatedBy    uuid.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Application users. One row per identity-provider subject.
type User struct {
	ID uuid.UUID
	// Identity-provider subject (Clerk). Never used as a primary or foreign key.
	ExternalID  string
	Email       string
	DisplayName *string
	AvatarUrl   *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// Tenant boundary. Every tenant-owned table references this.
type Workspace struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedBy uuid.UUID
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Invitations to join a workspace. Only the token hash is stored; the token is shown to the issuer once.
type WorkspaceInvitation struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       string
	Role        string
	// SHA-256 of the invitation token. Never store the token itself.
	TokenHash  []byte
	InvitedBy  uuid.UUID
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	AcceptedBy pgtype.UUID
	RevokedAt  pgtype.Timestamptz
	RevokedBy  pgtype.UUID
}

// Authorization record: a row here means the user may act in the workspace, at the given role.
type WorkspaceMember struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
