// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Append-only security log. Deliberately has no foreign keys so records outlive what they describe.
type AuditEvent struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ActorUserID pgtype.UUID
	Action      string
	Target      *string
	Detail      []byte
	OccurredAt  pgtype.Timestamptz
}

type GithubInstallation struct {
	ID                   uuid.UUID
	WorkspaceID          uuid.UUID
	GithubInstallationID int64
	AccountLogin         string
	AccountType          string
	RepositorySelection  string
	ConnectedBy          uuid.UUID
	SuspendedAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type GithubWebhookDelivery struct {
	DeliveryID string
	Event      string
	Action     *string
	ReceivedAt pgtype.Timestamptz
}

type Repository struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	InstallationID     uuid.UUID
	GithubRepositoryID int64
	Owner              string
	Name               string
	DefaultBranch      string
	Private            bool
	Granted            bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type RepositoryPermission struct {
	InstallationID uuid.UUID
	WorkspaceID    uuid.UUID
	Permission     string
	Access         string
	RecordedAt     pgtype.Timestamptz
}

// Application users. One row per identity-provider subject.
type User struct {
	ID uuid.UUID
	// Identity-provider subject (Clerk). Never used as a primary or foreign key.
	ExternalID  string
	Email       string
	DisplayName *string
	AvatarUrl   *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// Tenant boundary. Every tenant-owned table references this.
type Workspace struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedBy uuid.UUID
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Invitations to join a workspace. Only the token hash is stored; the token is shown to the issuer once.
type WorkspaceInvitation struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       string
	Role        string
	// SHA-256 of the invitation token. Never store the token itself.
	TokenHash  []byte
	InvitedBy  uuid.UUID
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	AcceptedBy pgtype.UUID
	RevokedAt  pgtype.Timestamptz
	RevokedBy  pgtype.UUID
}

// Authorization record: a row here means the user may act in the workspace, at the given role.
type WorkspaceMember struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
