// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
SELECT id, workspace_id, topic, subject_id, payload, attempts, available_at, leased_until, last_error, completed_at, created_at, claimant, terminated_at FROM weave_claim_outbox_batch($1::int, $2::interval, $3::int)
`

type ClaimOutboxBatchParams struct {
	BatchSize   int32
	Lease       pgtype.Interval
	MaxAttempts int32
}

// Take a batch of due rows, across every workspace, through the privileged
// function.
//
// Privileged because the publisher is the one caller that cannot have a
// workspace context — it polls every tenant's queue — and under FORCE
// row-level security an absent context matches no row, so a direct poll reads
// nothing and reports success. The function bounds its own arguments and
// returns rows carrying their `workspace_id`, which is what every write after
// the claim is scoped by: taken from the row, never from the caller.
func (q *Queries) ClaimOutboxBatch(ctx context.Context, arg ClaimOutboxBatchParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, arg.BatchSize, arg.Lease, arg.MaxAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Topic,
			&i.SubjectID,
			&i.Payload,
			&i.Attempts,
			&i.AvailableAt,
			&i.LeasedUntil,
			&i.LastError,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.Claimant,
			&i.TerminatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeOutboxEvent = `-- name: CompleteOutboxEvent :execrows
UPDATE outbox_events
SET completed_at = now(),
    leased_until = NULL,
    last_error   = NULL
WHERE id = $1 AND claimant = $2
  AND completed_at IS NULL AND terminated_at IS NULL
`

type CompleteOutboxEventParams struct {
	ID       uuid.UUID
	Claimant pgtype.UUID
}

// Fenced. A stale publisher marking someone else's claim done would hide work
// that is still owed.
func (q *Queries) CompleteOutboxEvent(ctx context.Context, arg CompleteOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeOutboxEvent, arg.ID, arg.Claimant)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOutboxEvent = `-- name: GetOutboxEvent :one
SELECT id, workspace_id, topic, subject_id, payload, attempts, available_at, leased_until, last_error, completed_at, created_at, claimant, terminated_at FROM outbox_events WHERE id = $1 AND workspace_id = $2
`

type GetOutboxEventParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Used by tests and by an operator looking at one row. Workspace-scoped like
// everything else, so a row id from one tenant is not readable through
// another.
func (q *Queries) GetOutboxEvent(ctx context.Context, arg GetOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEvent, arg.ID, arg.WorkspaceID)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Topic,
		&i.SubjectID,
		&i.Payload,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeasedUntil,
		&i.LastError,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.Claimant,
		&i.TerminatedAt,
	)
	return i, err
}

const releaseUnstartedOutboxEvent = `-- name: ReleaseUnstartedOutboxEvent :execrows
UPDATE outbox_events
SET leased_until = NULL,
    claimant     = NULL,
    attempts     = GREATEST(attempts - 1, 0)
WHERE id = $1 AND claimant = $2
  AND completed_at IS NULL AND terminated_at IS NULL
`

type ReleaseUnstartedOutboxEventParams struct {
	ID       uuid.UUID
	Claimant pgtype.UUID
}

// Give a row back that was claimed and never attempted.
//
// The claim increments `attempts` for the whole batch, which is deliberate: a
// publisher that dies mid-delivery must still burn one, or the ceiling that
// bounds the duplicate guarantee never applies to the case it exists for. But
// a row the publisher never got to — because the batch ran out of lease — has
// not been attempted at all, and spending an attempt on it would march it
// toward termination for no reason but our own slowness.
//
// So the attempt is given back, and `available_at` is left alone so the row is
// claimable immediately rather than pushed out like a failure. Fenced like
// every other settling update.
func (q *Queries) ReleaseUnstartedOutboxEvent(ctx context.Context, arg ReleaseUnstartedOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseUnstartedOutboxEvent, arg.ID, arg.Claimant)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryOutboxEvent = `-- name: RetryOutboxEvent :execrows
UPDATE outbox_events
SET leased_until = NULL,
    available_at = now() + $3::interval,
    last_error   = $4
WHERE id = $1 AND claimant = $2
  AND completed_at IS NULL AND terminated_at IS NULL
`

type RetryOutboxEventParams struct {
	ID        uuid.UUID
	Claimant  pgtype.UUID
	Backoff   pgtype.Interval
	LastError *string
}

// The delivery failed for a reason that might not recur: release the lease,
// record why, and push the row out by the caller's backoff.
//
// Fenced for the same reason completion is — a stale publisher pushing out
// someone else's row would delay work that is currently being done.
func (q *Queries) RetryOutboxEvent(ctx context.Context, arg RetryOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryOutboxEvent,
		arg.ID,
		arg.Claimant,
		arg.Backoff,
		arg.LastError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const terminateOutboxEvent = `-- name: TerminateOutboxEvent :execrows
UPDATE outbox_events
SET terminated_at = now(),
    leased_until  = NULL,
    last_error    = $3
WHERE id = $1 AND claimant = $2
  AND completed_at IS NULL AND terminated_at IS NULL
`

type TerminateOutboxEventParams struct {
	ID        uuid.UUID
	Claimant  pgtype.UUID
	LastError *string
}

// The delivery will never succeed, or has failed too many times to keep
// trying. The row stops being claimed and keeps its reason.
//
// Fenced like the other two. The first version of the M5.1 spec fenced
// "completion and retry" and left this one out, which would have let a stale
// publisher quarantine the row that replaced it.
func (q *Queries) TerminateOutboxEvent(ctx context.Context, arg TerminateOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, terminateOutboxEvent, arg.ID, arg.Claimant, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
