// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_credentials.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateProviderCredential = `-- name: ActivateProviderCredential :one
UPDATE workspace_provider_credentials SET state='active',epoch=epoch+1,current_version_id=$4,updated_at=now()
WHERE workspace_id=$1 AND provider=$2 AND epoch=$3 RETURNING id, workspace_id, provider, state, epoch, current_version_id, created_by, created_at, updated_at
`

type ActivateProviderCredentialParams struct {
	WorkspaceID      uuid.UUID
	Provider         string
	Epoch            int64
	CurrentVersionID pgtype.UUID
}

func (q *Queries) ActivateProviderCredential(ctx context.Context, arg ActivateProviderCredentialParams) (WorkspaceProviderCredential, error) {
	row := q.db.QueryRow(ctx, activateProviderCredential,
		arg.WorkspaceID,
		arg.Provider,
		arg.Epoch,
		arg.CurrentVersionID,
	)
	var i WorkspaceProviderCredential
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.State,
		&i.Epoch,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableProviderCredential = `-- name: DisableProviderCredential :one
UPDATE workspace_provider_credentials SET state='revoked',epoch=epoch+1,updated_at=now()
WHERE workspace_id=$1 AND provider=$2 AND epoch=$3 AND state='active' RETURNING id, workspace_id, provider, state, epoch, current_version_id, created_by, created_at, updated_at
`

type DisableProviderCredentialParams struct {
	WorkspaceID uuid.UUID
	Provider    string
	Epoch       int64
}

func (q *Queries) DisableProviderCredential(ctx context.Context, arg DisableProviderCredentialParams) (WorkspaceProviderCredential, error) {
	row := q.db.QueryRow(ctx, disableProviderCredential, arg.WorkspaceID, arg.Provider, arg.Epoch)
	var i WorkspaceProviderCredential
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.State,
		&i.Epoch,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedCredentialResource = `-- name: GetOwnedCredentialResource :one
SELECT id, workspace_id, credential_id, environment, project_number, secret_id, created_at FROM provider_credential_resources
WHERE project_number=$1 AND secret_id=$2 AND workspace_id=$3 AND credential_id=$4
`

type GetOwnedCredentialResourceParams struct {
	ProjectNumber string
	SecretID      uuid.UUID
	WorkspaceID   uuid.UUID
	CredentialID  uuid.UUID
}

func (q *Queries) GetOwnedCredentialResource(ctx context.Context, arg GetOwnedCredentialResourceParams) (ProviderCredentialResource, error) {
	row := q.db.QueryRow(ctx, getOwnedCredentialResource,
		arg.ProjectNumber,
		arg.SecretID,
		arg.WorkspaceID,
		arg.CredentialID,
	)
	var i ProviderCredentialResource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CredentialID,
		&i.Environment,
		&i.ProjectNumber,
		&i.SecretID,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderCredentialBinding = `-- name: GetProviderCredentialBinding :one
SELECT id, workspace_id, provider, state, epoch, current_version_id, created_by, created_at, updated_at FROM workspace_provider_credentials WHERE workspace_id=$1 AND provider=$2
`

type GetProviderCredentialBindingParams struct {
	WorkspaceID uuid.UUID
	Provider    string
}

func (q *Queries) GetProviderCredentialBinding(ctx context.Context, arg GetProviderCredentialBindingParams) (WorkspaceProviderCredential, error) {
	row := q.db.QueryRow(ctx, getProviderCredentialBinding, arg.WorkspaceID, arg.Provider)
	var i WorkspaceProviderCredential
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.State,
		&i.Epoch,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProviderCredentialBinding = `-- name: InsertProviderCredentialBinding :one
INSERT INTO workspace_provider_credentials(id,workspace_id,provider,created_by)
VALUES($1,$2,$3,$4) RETURNING id, workspace_id, provider, state, epoch, current_version_id, created_by, created_at, updated_at
`

type InsertProviderCredentialBindingParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Provider    string
	CreatedBy   uuid.UUID
}

func (q *Queries) InsertProviderCredentialBinding(ctx context.Context, arg InsertProviderCredentialBindingParams) (WorkspaceProviderCredential, error) {
	row := q.db.QueryRow(ctx, insertProviderCredentialBinding,
		arg.ID,
		arg.WorkspaceID,
		arg.Provider,
		arg.CreatedBy,
	)
	var i WorkspaceProviderCredential
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.State,
		&i.Epoch,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProviderCredentialResource = `-- name: InsertProviderCredentialResource :one
INSERT INTO provider_credential_resources(id,workspace_id,credential_id,environment,project_number,secret_id)
VALUES($1,$2,$3,$4,$5,$6)
ON CONFLICT(project_number,secret_id) DO NOTHING RETURNING id, workspace_id, credential_id, environment, project_number, secret_id, created_at
`

type InsertProviderCredentialResourceParams struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	CredentialID  uuid.UUID
	Environment   string
	ProjectNumber string
	SecretID      uuid.UUID
}

func (q *Queries) InsertProviderCredentialResource(ctx context.Context, arg InsertProviderCredentialResourceParams) (ProviderCredentialResource, error) {
	row := q.db.QueryRow(ctx, insertProviderCredentialResource,
		arg.ID,
		arg.WorkspaceID,
		arg.CredentialID,
		arg.Environment,
		arg.ProjectNumber,
		arg.SecretID,
	)
	var i ProviderCredentialResource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CredentialID,
		&i.Environment,
		&i.ProjectNumber,
		&i.SecretID,
		&i.CreatedAt,
	)
	return i, err
}

const insertProviderCredentialVersion = `-- name: InsertProviderCredentialVersion :exec
INSERT INTO provider_credential_versions(id,workspace_id,credential_id,resource_id,secret_version,registration_epoch,verification_id,created_by)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertProviderCredentialVersionParams struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	CredentialID      uuid.UUID
	ResourceID        uuid.UUID
	SecretVersion     int64
	RegistrationEpoch int64
	VerificationID    uuid.UUID
	CreatedBy         uuid.UUID
}

func (q *Queries) InsertProviderCredentialVersion(ctx context.Context, arg InsertProviderCredentialVersionParams) error {
	_, err := q.db.Exec(ctx, insertProviderCredentialVersion,
		arg.ID,
		arg.WorkspaceID,
		arg.CredentialID,
		arg.ResourceID,
		arg.SecretVersion,
		arg.RegistrationEpoch,
		arg.VerificationID,
		arg.CreatedBy,
	)
	return err
}
