// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"context"
)

type Querier interface {
	// Test and operator support only; not used on a request path.
	CountUsers(ctx context.Context) (int64, error)
	GetUserByExternalID(ctx context.Context, externalID string) (User, error)
	// Just-in-time provisioning. ON CONFLICT makes concurrent first requests for
	// the same subject resolve to a single row instead of racing, and DO UPDATE
	// (rather than DO NOTHING) guarantees RETURNING yields the row either way.
	UpsertUserByExternalID(ctx context.Context, arg UpsertUserByExternalIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
