// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateProviderCredential(ctx context.Context, arg ActivateProviderCredentialParams) (WorkspaceProviderCredential, error)
	AddSessionParticipant(ctx context.Context, arg AddSessionParticipantParams) (SessionParticipant, error)
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error)
	AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AuditEvent, error)
	// DO NOTHING on the deduplication key, so a duplicate returns no row rather
	// than an error — the caller distinguishes it without parsing a message.
	AppendSessionEvent(ctx context.Context, arg AppendSessionEventParams) (int64, error)
	// Append-only, enforced by trigger as well as by there being no other
	// statement that touches this table.
	AppendSessionTransition(ctx context.Context, arg AppendSessionTransitionParams) (SessionStateTransition, error)
	// The claim, as one statement rather than a check followed by an insert.
	//
	// ON CONFLICT DO UPDATE rather than DO NOTHING, because the conflict has two
	// meanings and only the update can tell them apart while taking the lease: a
	// row whose lease has expired and which never completed is a claim whose
	// holder died, and it is claimable again; anything else is either in flight or
	// complete and must not be disturbed.
	//
	// The WHERE on the update is what makes that safe. It also requires the
	// fingerprint to match, so a reclaim with a *different* request does not
	// quietly overwrite what the first attempt asked for — it falls through to the
	// read below and is reported as the mismatch it is.
	//
	// `claimant` is reissued on every claim. It is the fencing token: a holder
	// that was slow rather than dead must not be able to complete or release the
	// claim that replaced it.
	ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (IdempotencyKey, error)
	// Single-statement claim: the WHERE clause is what makes the token single
	// use. Two concurrent accepts race here and exactly one matches a row, so no
	// lock is needed and no second membership can be created.
	ClaimInvitation(ctx context.Context, arg ClaimInvitationParams) (WorkspaceInvitation, error)
	// Take a batch of due rows, across every workspace, through the privileged
	// function.
	//
	// Privileged because the publisher is the one caller that cannot have a
	// workspace context — it polls every tenant's queue — and under FORCE
	// row-level security an absent context matches no row, so a direct poll reads
	// nothing and reports success. The function bounds its own arguments and
	// returns rows carrying their `workspace_id`, which is what every write after
	// the claim is scoped by: taken from the row, never from the caller.
	ClaimOutboxBatch(ctx context.Context, arg ClaimOutboxBatchParams) ([]OutboxEvent, error)
	ClearInstallationPermissions(ctx context.Context, arg ClearInstallationPermissionsParams) error
	// Written in the same transaction as the work it describes. A response
	// recorded afterwards could fail while the work stood, and the expiring lease
	// would then let a retry do the work a second time.
	//
	// Fenced on `claimant`: a holder whose lease expired while it was still
	// running must not write over the record belonging to whoever reclaimed the
	// key. Returning the row count is what lets the caller notice that happened.
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (int64, error)
	// Fenced. A stale publisher marking someone else's claim done would hide work
	// that is still owed.
	CompleteOutboxEvent(ctx context.Context, arg CompleteOutboxEventParams) (int64, error)
	// Mark a delivery's effect durable. Until this runs, a retry may reclaim it.
	CompleteWebhookDelivery(ctx context.Context, deliveryID string) error
	// Bind an installation to a workspace.
	//
	// No ON CONFLICT clause on purpose. The unique index on
	// github_installation_id is what refuses a second binding, and the refusal
	// must reach the caller as an error rather than be absorbed into an update:
	// quietly rebinding would move a repository grant between tenants.
	ConnectInstallation(ctx context.Context, arg ConnectInstallationParams) (GithubInstallation, error)
	// Test and operator support only; not used on a request path.
	CountUsers(ctx context.Context) (int64, error)
	CountWorkspaceEgressHosts(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	// Used under LockWorkspace to enforce that a workspace never loses its last
	// owner.
	CountWorkspaceOwners(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	// Append-only: there is no update or delete for this table, and the triggers
	// refuse both. Editing a profile means writing another row.
	CreateAgentVersion(ctx context.Context, arg CreateAgentVersionParams) (AgentVersion, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (WorkspaceInvitation, error)
	// Fails on runners_one_live_per_session if the session already has a live
	// runner; the caller reads that one instead of making a second.
	CreateRunner(ctx context.Context, arg CreateRunnerParams) (Runner, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// No RETURNING. Under RLS, PostgreSQL applies the workspaces *read* policy to
	// returned rows, and that policy shows a workspace only to its members — none
	// exist yet, in the statement that creates it. The store reads the row back
	// after inserting the owner's membership.
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error
	DeleteWorkspaceEgressHost(ctx context.Context, arg DeleteWorkspaceEgressHostParams) (WorkspaceEgressHost, error)
	DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) (int64, error)
	DisableProviderCredential(ctx context.Context, arg DisableProviderCredentialParams) (WorkspaceProviderCredential, error)
	// The terminal write, after the backend confirms the environment is gone.
	// Conditional on the runner being live, so a redelivered teardown finds no
	// row and treats that as already done.
	EndRunner(ctx context.Context, arg EndRunnerParams) (Runner, error)
	// Written in the same transaction as the thing it promises. That is the whole
	// mechanism: writing the session and then publishing leaves a window where the
	// session exists and nothing will pick it up, open exactly when the process
	// dies.
	EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) (OutboxEvent, error)
	GetAgentForWorkspace(ctx context.Context, arg GetAgentForWorkspaceParams) (Agent, error)
	GetAgentVersionForWorkspace(ctx context.Context, arg GetAgentVersionForWorkspaceParams) (AgentVersion, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetInstallationByGitHubIDForWorkspace(ctx context.Context, arg GetInstallationByGitHubIDForWorkspaceParams) (GithubInstallation, error)
	// Scoped by workspace, so an installation id from one tenant cannot be read
	// through another even before the policies are consulted.
	GetInstallationForWorkspace(ctx context.Context, arg GetInstallationForWorkspaceParams) (GithubInstallation, error)
	// Deliberately unscoped by workspace: the token is the only thing the
	// acceptor holds, and they are not yet a member of anything. The caller
	// checks status and email before acting on the result.
	//
	// Goes through weave_invitation_by_token rather than the table, because
	// row-level security would otherwise match no row — there is no workspace
	// context to match against. The function is SECURITY DEFINER and returns only
	// the row whose hash was presented.
	GetInvitationByTokenHash(ctx context.Context, presentedHash []byte) (WorkspaceInvitation, error)
	// Scoped by workspace so an invitation id from one tenant cannot be revoked
	// through another.
	GetInvitationForWorkspace(ctx context.Context, arg GetInvitationForWorkspaceParams) (WorkspaceInvitation, error)
	GetLiveRunnerForSession(ctx context.Context, arg GetLiveRunnerForSessionParams) (Runner, error)
	// Used by tests and by an operator looking at one row. Workspace-scoped like
	// everything else, so a row id from one tenant is not readable through
	// another.
	GetOutboxEvent(ctx context.Context, arg GetOutboxEventParams) (OutboxEvent, error)
	// The row occupying the one-outstanding slot, if any. May be expired: the
	// unique index predicate cannot reference now(), so the caller decides.
	GetOutstandingInvitationForEmail(ctx context.Context, arg GetOutstandingInvitationForEmailParams) (WorkspaceInvitation, error)
	GetOwnedCredentialResource(ctx context.Context, arg GetOwnedCredentialResourceParams) (ProviderCredentialResource, error)
	GetProviderCredentialBinding(ctx context.Context, arg GetProviderCredentialBindingParams) (WorkspaceProviderCredential, error)
	GetRepositoryForWorkspace(ctx context.Context, arg GetRepositoryForWorkspaceParams) (Repository, error)
	GetRunner(ctx context.Context, arg GetRunnerParams) (Runner, error)
	GetRunnerEgressSnapshot(ctx context.Context, arg GetRunnerEgressSnapshotParams) (RunnerEgressSnapshot, error)
	// Scoped by workspace, so a session id from one tenant cannot be read through
	// another even before the policies are consulted.
	GetSessionForWorkspace(ctx context.Context, arg GetSessionForWorkspaceParams) (Session, error)
	// No mutable task/current-agent join and no legacy fallback. Settings come from
	// the frozen version pin; task text comes from its creation-time snapshot.
	GetSessionInputForWorkspace(ctx context.Context, arg GetSessionInputForWorkspaceParams) (GetSessionInputForWorkspaceRow, error)
	// Scoped by workspace, so a task id from one tenant cannot be read through
	// another even before the policies are consulted.
	GetTaskForWorkspace(ctx context.Context, arg GetTaskForWorkspaceParams) (Task, error)
	GetUserByExternalID(ctx context.Context, externalID string) (User, error)
	GetWorkspaceEgressHost(ctx context.Context, arg GetWorkspaceEgressHostParams) (WorkspaceEgressHost, error)
	// Scoped by member, not just by id. A caller who is not a member gets no row,
	// so "not found" and "not yours" are indistinguishable from the outside and
	// workspace identifiers cannot be probed.
	GetWorkspaceForMember(ctx context.Context, arg GetWorkspaceForMemberParams) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error)
	InsertProviderCredentialBinding(ctx context.Context, arg InsertProviderCredentialBindingParams) (WorkspaceProviderCredential, error)
	InsertProviderCredentialResource(ctx context.Context, arg InsertProviderCredentialResourceParams) (ProviderCredentialResource, error)
	InsertProviderCredentialVersion(ctx context.Context, arg InsertProviderCredentialVersionParams) error
	// Recorded before the proxy forwards the request. Runs in the tenant context
	// of the runner's workspace; RLS refuses any other.
	InsertRegistryRequest(ctx context.Context, arg InsertRegistryRequestParams) error
	InsertWorkspaceEgressHost(ctx context.Context, arg InsertWorkspaceEgressHostParams) (WorkspaceEgressHost, error)
	// What the workspace currently has connected. Removed installations are kept
	// for their repository history but are not connections any more.
	ListActiveInstallationsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]GithubInstallation, error)
	ListAgentVersionsForWorkspace(ctx context.Context, arg ListAgentVersionsForWorkspaceParams) ([]AgentVersion, error)
	ListAgentsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Agent, error)
	// Operator and test support.
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListInstallationPermissions(ctx context.Context, arg ListInstallationPermissionsParams) ([]RepositoryPermission, error)
	ListInvitationsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListInvitationsForWorkspaceRow, error)
	// Reads what a claimer would find, without claiming it.
	//
	// `leased_until` is a lease and not a flag: a row whose lease has expired is
	// pending again, because the publisher holding it died and no operator is
	// going to notice a boolean nobody will ever clear. The claim itself lands in
	// M5 as a single conditional UPDATE, so that two claimers cannot both win.
	ListPendingOutboxEvents(ctx context.Context, workspaceID uuid.UUID) ([]OutboxEvent, error)
	// A session's registry requests, oldest first. Tenant-scoped.
	ListRegistryRequests(ctx context.Context, arg ListRegistryRequestsParams) ([]RegistryRequest, error)
	// Withdrawn repositories are returned too, with granted = false, so the
	// interface can say "access was removed" rather than silently dropping a
	// repository someone was using yesterday.
	//
	// Repositories belonging to a removed installation are excluded. Their rows
	// are kept for audit and for reading finished sessions, but the connection is
	// gone, so listing them among a workspace's repositories would present history
	// as current state — and they would match no connected account in the
	// interface, which reads as a build mismatch.
	ListRepositoriesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Repository, error)
	// For tests and, later, the session room. Scoped by workspace as well as the
	// policy, and ordered by the sequence — never by occurred_at, which is a claim.
	ListSessionEvents(ctx context.Context, arg ListSessionEventsParams) ([]SessionEvent, error)
	ListSessionParticipants(ctx context.Context, arg ListSessionParticipantsParams) ([]SessionParticipant, error)
	ListSessionTransitions(ctx context.Context, arg ListSessionTransitionsParams) ([]SessionStateTransition, error)
	ListSessionsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Session, error)
	ListTasksForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Task, error)
	ListWorkspaceEgressHosts(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceEgressHost, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error)
	ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error)
	// Taken before computing the next version number. Without it two concurrent
	// edits both read the same MAX(version) and one fails on the unique index —
	// an error the caller can do nothing useful with.
	LockAgentForUpdate(ctx context.Context, arg LockAgentForUpdateParams) (Agent, error)
	// Taken by a transition into a terminal state, before it writes the state.
	//
	// Creates the counter if the session has emitted nothing yet, so the lock
	// always has a row to take. Exclusive, like every append's increment, so the
	// two queue fairly: a terminal transition waits for at most the appends
	// already holding or queued for the row, never for an unbounded stream.
	LockSessionEventSequence(ctx context.Context, arg LockSessionEventSequenceParams) error
	// Taken before a state change. The version read here is the one the change is
	// checked against, and holding the lock is what stops two transitions reading
	// the same version and both believing they are current.
	//
	// NO KEY UPDATE rather than UPDATE, because nothing that takes this lock
	// changes a key column. The difference matters since M5.3: every event
	// appended for a session makes a foreign-key check that takes FOR KEY SHARE
	// on this row, and plain FOR UPDATE conflicts with that — so under continuous
	// output a transition queued behind an unbounded stream of appends, and a
	// terminal transition holding this row while waiting for the event counter
	// would deadlock with an append holding the counter while its FK check
	// waited for this row. NO KEY UPDATE still serialises transitions and branch
	// recording against each other, which is all it was ever for.
	LockSessionForUpdate(ctx context.Context, arg LockSessionForUpdateParams) (Session, error)
	// Read at the start of a patch, in the transaction that writes it.
	//
	// What makes a patch safe is that the read happens here rather than in an
	// earlier transaction: a read-modify-write split across two transactions lets
	// two concurrent edits to different fields both read the same row, the second
	// writing its own field alongside stale copies of the rest and silently
	// undoing the first. That was measured — reproducing the split shape fails the
	// concurrency test every run.
	//
	// FOR UPDATE is not what prevents it today. authorizeActor takes LockWorkspace
	// before this runs, which already serializes every mutation in a workspace, so
	// this narrower lock is redundant in the current arrangement — the same
	// relationship LockAgentForUpdate has. It is here so this transaction states
	// the row it depends on rather than relying on the workspace lock staying as
	// coarse as it is.
	LockTaskForUpdate(ctx context.Context, arg LockTaskForUpdateParams) (Task, error)
	// Serialises membership changes within a workspace. Taken before any check
	// that counts owners, so two concurrent demotions cannot both observe two
	// owners and both proceed.
	LockWorkspace(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// Used when GitHub reports the installation removed.
	//
	// The row is marked, not deleted. Deleting it cascades to the repositories,
	// and those rows are the record that access once existed — which is what makes
	// an old audit entry or a finished session readable. Withdrawing the
	// repositories is a separate statement in the same transaction.
	MarkInstallationDeleted(ctx context.Context, arg MarkInstallationDeletedParams) error
	MarkRunnerRunning(ctx context.Context, arg MarkRunnerRunningParams) (Runner, error)
	// Taken before the backend is asked to destroy anything, so a crash mid-
	// teardown leaves a runner the reconciler knows to finish. updated_at marks
	// only the move into terminating: the reconciler bounds how long it leaves a
	// halted runner by it, and a retried teardown must not restart that clock.
	MarkRunnerTerminating(ctx context.Context, arg MarkRunnerTerminatingParams) (Runner, error)
	// Read under the agent's row lock by the caller, so two concurrent edits
	// cannot both compute the same next number and collide on the unique index.
	NextAgentVersionNumber(ctx context.Context, arg NextAgentVersionNumberParams) (int32, error)
	// Takes the next number for a session, creating its counter on first use.
	//
	// The upsert locks the counter row until the transaction ends, which is what
	// serialises two ingestor replicas on one session. If the insert that follows
	// is a duplicate, the caller rolls back, and the number goes with it.
	NextSessionEventSequence(ctx context.Context, arg NextSessionEventSequenceParams) (int64, error)
	// Retention, through a SECURITY DEFINER function.
	//
	// The sweep runs from a background goroutine with no tenant context, and under
	// FORCE row-level security every policy then matches nothing — so a direct
	// DELETE removes no rows and reports success, which is retention silently not
	// happening. The same problem invitations-by-token had, and the same answer
	// ADR-012 settled on: a function owned by a role that may look past the
	// policies, scoped so narrowly that it can do nothing else.
	PruneIdempotencyKeys(ctx context.Context, retention pgtype.Interval) (int64, error)
	// Deliveries are only needed while deduplication might see a retry. GitHub
	// gives up well inside this window.
	PruneWebhookDeliveries(ctx context.Context, retention pgtype.Interval) error
	QuarantineSessionEvent(ctx context.Context, arg QuarantineSessionEventParams) error
	RecordInstallationPermission(ctx context.Context, arg RecordInstallationPermissionParams) error
	// Sets the branch commit once. `branch_sha IS NULL` is the application's half
	// of write-once; the trigger in 00010 is the database's.
	//
	// The version is deliberately not bumped. It exists to stop two *state*
	// changes colliding, and recording the branch is not one: the branch is cut
	// while the session stays in `provisioning`. Bumping it would make a member's pause or cancel fail as a
	// conflict against a change that did not touch the state they read.
	RecordSessionBranch(ctx context.Context, arg RecordSessionBranchParams) (Session, error)
	// Deduplication. GitHub retries deliveries, and a retry must not produce a
	// second effect.
	//
	// ON CONFLICT DO NOTHING with a RETURNING clause yields no row when the
	// delivery has been seen, which is how the caller distinguishes the two
	// without a separate read and the race that would come with it.
	RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) (GithubWebhookDelivery, error)
	// The work failed, so the key is released at once rather than making a
	// legitimate retry wait out the lease. Fenced for the same reason completion
	// is: a late holder must not delete the claim that replaced it. Guarded on not
	// being complete, so a late release cannot erase a finished record.
	ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) (int64, error)
	// Give a row back that was claimed and never attempted.
	//
	// The claim increments `attempts` for the whole batch, which is deliberate: a
	// publisher that dies mid-delivery must still burn one, or the ceiling that
	// bounds the duplicate guarantee never applies to the case it exists for. But
	// a row the publisher never got to — because the batch ran out of lease — has
	// not been attempted at all, and spending an attempt on it would march it
	// toward termination for no reason but our own slowness.
	//
	// So the attempt is given back, and `available_at` is left alone so the row is
	// claimable immediately rather than pushed out like a failure. Fenced like
	// every other settling update.
	ReleaseUnstartedOutboxEvent(ctx context.Context, arg ReleaseUnstartedOutboxEventParams) (int64, error)
	RenameAgent(ctx context.Context, arg RenameAgentParams) (Agent, error)
	// Optimistic concurrency: the caller supplies the version it read. A stale
	// version matches no row, which the store reports as a conflict rather than
	// silently overwriting a concurrent edit.
	RenameWorkspace(ctx context.Context, arg RenameWorkspaceParams) (Workspace, error)
	// The delivery failed for a reason that might not recur: release the lease,
	// record why, and push the row out by the caller's backoff.
	//
	// Fenced for the same reason completion is — a stale publisher pushing out
	// someone else's row would delay work that is currently being done.
	RetryOutboxEvent(ctx context.Context, arg RetryOutboxEventParams) (int64, error)
	// Only an outstanding invitation can be revoked; revoking an accepted or
	// already-revoked one matches no row.
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (WorkspaceInvitation, error)
	// Whether a producer is a live runner of this session. Read inside the event
	// append transaction, without a lock, after the event counter is taken.
	//
	// `terminating` counts. Teardown marks the runner terminating *before* it
	// asks the backend to destroy anything, so a runner's last events — flushed
	// as it is stopped — arrive while its row reads terminating. They are that
	// session's history, from that session's runner; refusing them would record
	// a normal shutdown as an intrusion. Once the backend confirms the
	// environment is gone the row reads terminated, and nothing more is accepted.
	RunnerBoundToSession(ctx context.Context, arg RunnerBoundToSessionParams) (bool, error)
	// Whether an event is already stored, for a terminal session: a redelivery of
	// an event stored before the session ended is a duplicate, not a refusal.
	SessionEventExists(ctx context.Context, arg SessionEventExistsParams) (bool, error)
	// The first provider.failed a session's history holds, if any. Read after the
	// drain, so the history is complete. The code is a validated stable identifier
	// (domain.DecodeEvent); the provider's message text is never read here.
	SessionProviderFailure(ctx context.Context, arg SessionProviderFailureParams) (string, error)
	// The session's state, read inside the append transaction **after** the
	// counter row is locked — never under a lock on the session row itself.
	//
	// An earlier revision took FOR SHARE on the session here. Measured under
	// continuous output, it starved transitions: new share lockers kept jumping a
	// waiting FOR UPDATE, and a terminal transition waited the whole three-second
	// run. The counter row is the serialisation point instead (see
	// LockSessionEventSequence): a terminal transition locks it too, so either
	// the transition commits first and this read — a fresh snapshot, since the
	// lock was taken by an earlier statement — sees it, or the append commits
	// first and the transition waits for exactly that one append.
	SessionStateForEvent(ctx context.Context, arg SessionStateForEventParams) (string, error)
	// The pointer is the only mutable thing about a profile. Moving it changes
	// what the next session will use and nothing about what past sessions did.
	SetAgentCurrentVersion(ctx context.Context, arg SetAgentCurrentVersionParams) (Agent, error)
	SetInstallationSelection(ctx context.Context, arg SetInstallationSelectionParams) (GithubInstallation, error)
	// Suspension is recorded, never deleted. Unsuspending must restore the
	// previous state rather than require a fresh install, and keeping the rows is
	// what makes that possible.
	SetInstallationSuspended(ctx context.Context, arg SetInstallationSuspendedParams) (GithubInstallation, error)
	// Recorded as soon as the backend returns one, so a crash after this point
	// leaves something to tear down rather than an environment nothing names.
	SetRunnerHandle(ctx context.Context, arg SetRunnerHandleParams) (Runner, error)
	SlugExists(ctx context.Context, slug string) (bool, error)
	// The delivery will never succeed, or has failed too many times to keep
	// trying. The row stops being claimed and keeps its reason.
	//
	// Fenced like the other two. The first version of the M5.1 spec fenced
	// "completion and retry" and left this one out, which would have let a stale
	// publisher quarantine the row that replaced it.
	TerminateOutboxEvent(ctx context.Context, arg TerminateOutboxEventParams) (int64, error)
	// The version predicate is belt-and-braces behind LockSessionForUpdate: the
	// lock already serialises writers, and this refuses to write at all if the row
	// moved between the two — which is the thing that must never silently happen.
	UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) (Session, error)
	// The body is written back exactly as given. Nothing here normalises it: the
	// stored value and the returned value must agree, or nobody can tell what is
	// actually stored.
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (WorkspaceMember, error)
	// Reconciliation writes every repository GitHub currently grants.
	//
	// ON CONFLICT updates rather than inserts because a repository seen before may
	// have been renamed, transferred, made private, or re-granted after being
	// withdrawn. The conflict target is (installation_id, github_repository_id):
	// the GitHub id is the identity, and owner/name are mutable descriptions of it.
	UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (Repository, error)
	// Just-in-time provisioning. ON CONFLICT makes concurrent first requests for
	// the same subject resolve to a single row instead of racing, and DO UPDATE
	// (rather than DO NOTHING) guarantees RETURNING yields the row either way.
	UpsertUserByExternalID(ctx context.Context, arg UpsertUserByExternalIDParams) (User, error)
	WithdrawAllRepositories(ctx context.Context, arg WithdrawAllRepositoriesParams) error
	// Mark everything the installation no longer grants.
	//
	// Rows are withdrawn rather than deleted: the record that access once existed
	// is what makes an old audit entry or session readable later. Passing the
	// currently granted set and negating it, rather than deleting named ones,
	// means a repository that vanished without an event is still caught.
	WithdrawRepositoriesNotIn(ctx context.Context, arg WithdrawRepositoriesNotInParams) error
	WorkspaceEgressHostExists(ctx context.Context, arg WorkspaceEgressHostExistsParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
