// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
)

const insertRegistryRequest = `-- name: InsertRegistryRequest :exec
INSERT INTO registry_requests (id, workspace_id, session_id, runner_id, host, method, path)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
`

type InsertRegistryRequestParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	SessionID   uuid.UUID
	RunnerID    uuid.UUID
	Host        string
	Method      string
	Path        string
}

// Recorded before the proxy forwards the request. Runs in the tenant context
// of the runner's workspace; RLS refuses any other.
func (q *Queries) InsertRegistryRequest(ctx context.Context, arg InsertRegistryRequestParams) error {
	_, err := q.db.Exec(ctx, insertRegistryRequest,
		arg.ID,
		arg.WorkspaceID,
		arg.SessionID,
		arg.RunnerID,
		arg.Host,
		arg.Method,
		arg.Path,
	)
	return err
}

const listRegistryRequests = `-- name: ListRegistryRequests :many
SELECT id, workspace_id, session_id, runner_id, host, method, path, requested_at
FROM registry_requests
WHERE session_id = $1 AND workspace_id = $2
ORDER BY requested_at, id
`

type ListRegistryRequestsParams struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
}

// A session's registry requests, oldest first. Tenant-scoped.
func (q *Queries) ListRegistryRequests(ctx context.Context, arg ListRegistryRequestsParams) ([]RegistryRequest, error) {
	rows, err := q.db.Query(ctx, listRegistryRequests, arg.SessionID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistryRequest{}
	for rows.Next() {
		var i RegistryRequest
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SessionID,
			&i.RunnerID,
			&i.Host,
			&i.Method,
			&i.Path,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
