// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runners.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
)

const createRunner = `-- name: CreateRunner :one
INSERT INTO runners (id, session_id, workspace_id, backend)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, workspace_id, backend, backend_handle, state, failure_reason, created_at, ready_at, terminated_at, updated_at
`

type CreateRunnerParams struct {
	ID          uuid.UUID
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
	Backend     string
}

// Fails on runners_one_live_per_session if the session already has a live
// runner; the caller reads that one instead of making a second.
func (q *Queries) CreateRunner(ctx context.Context, arg CreateRunnerParams) (Runner, error) {
	row := q.db.QueryRow(ctx, createRunner,
		arg.ID,
		arg.SessionID,
		arg.WorkspaceID,
		arg.Backend,
	)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkspaceID,
		&i.Backend,
		&i.BackendHandle,
		&i.State,
		&i.FailureReason,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.TerminatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endRunner = `-- name: EndRunner :one
UPDATE runners
SET state = $1, failure_reason = $2,
    terminated_at = now(), updated_at = now()
WHERE id = $3 AND workspace_id = $4
  AND state IN ('provisioning', 'running', 'terminating')
RETURNING id, session_id, workspace_id, backend, backend_handle, state, failure_reason, created_at, ready_at, terminated_at, updated_at
`

type EndRunnerParams struct {
	EndState      string
	FailureReason *string
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
}

// The terminal write, after the backend confirms the environment is gone.
// Conditional on the runner being live, so a redelivered teardown finds no
// row and treats that as already done.
func (q *Queries) EndRunner(ctx context.Context, arg EndRunnerParams) (Runner, error) {
	row := q.db.QueryRow(ctx, endRunner,
		arg.EndState,
		arg.FailureReason,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkspaceID,
		&i.Backend,
		&i.BackendHandle,
		&i.State,
		&i.FailureReason,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.TerminatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveRunnerForSession = `-- name: GetLiveRunnerForSession :one
SELECT id, session_id, workspace_id, backend, backend_handle, state, failure_reason, created_at, ready_at, terminated_at, updated_at FROM runners
WHERE session_id = $1 AND workspace_id = $2
  AND state IN ('provisioning', 'running', 'terminating')
`

type GetLiveRunnerForSessionParams struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetLiveRunnerForSession(ctx context.Context, arg GetLiveRunnerForSessionParams) (Runner, error) {
	row := q.db.QueryRow(ctx, getLiveRunnerForSession, arg.SessionID, arg.WorkspaceID)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkspaceID,
		&i.Backend,
		&i.BackendHandle,
		&i.State,
		&i.FailureReason,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.TerminatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunner = `-- name: GetRunner :one
SELECT id, session_id, workspace_id, backend, backend_handle, state, failure_reason, created_at, ready_at, terminated_at, updated_at FROM runners
WHERE id = $1 AND workspace_id = $2
`

type GetRunnerParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetRunner(ctx context.Context, arg GetRunnerParams) (Runner, error) {
	row := q.db.QueryRow(ctx, getRunner, arg.ID, arg.WorkspaceID)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkspaceID,
		&i.Backend,
		&i.BackendHandle,
		&i.State,
		&i.FailureReason,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.TerminatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRunnerRunning = `-- name: MarkRunnerRunning :one
UPDATE runners
SET state = 'running', ready_at = now(), updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND state = 'provisioning'
RETURNING id, session_id, workspace_id, backend, backend_handle, state, failure_reason, created_at, ready_at, terminated_at, updated_at
`

type MarkRunnerRunningParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) MarkRunnerRunning(ctx context.Context, arg MarkRunnerRunningParams) (Runner, error) {
	row := q.db.QueryRow(ctx, markRunnerRunning, arg.ID, arg.WorkspaceID)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkspaceID,
		&i.Backend,
		&i.BackendHandle,
		&i.State,
		&i.FailureReason,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.TerminatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRunnerTerminating = `-- name: MarkRunnerTerminating :one
UPDATE runners
SET state = 'terminating', updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND state IN ('provisioning', 'running', 'terminating')
RETURNING id, session_id, workspace_id, backend, backend_handle, state, failure_reason, created_at, ready_at, terminated_at, updated_at
`

type MarkRunnerTerminatingParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Taken before the backend is asked to destroy anything, so a crash mid-
// teardown leaves a runner the reconciler knows to finish.
func (q *Queries) MarkRunnerTerminating(ctx context.Context, arg MarkRunnerTerminatingParams) (Runner, error) {
	row := q.db.QueryRow(ctx, markRunnerTerminating, arg.ID, arg.WorkspaceID)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkspaceID,
		&i.Backend,
		&i.BackendHandle,
		&i.State,
		&i.FailureReason,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.TerminatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runnerBoundToSession = `-- name: RunnerBoundToSession :one
SELECT EXISTS (
    SELECT 1 FROM runners
    WHERE id = $1 AND session_id = $2 AND state IN ('provisioning', 'running')
)
`

type RunnerBoundToSessionParams struct {
	ID        uuid.UUID
	SessionID uuid.UUID
}

// Whether a producer is a live runner of this session. Read inside the event
// append transaction, without a lock, after the event counter is taken.
func (q *Queries) RunnerBoundToSession(ctx context.Context, arg RunnerBoundToSessionParams) (bool, error) {
	row := q.db.QueryRow(ctx, runnerBoundToSession, arg.ID, arg.SessionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setRunnerHandle = `-- name: SetRunnerHandle :one
UPDATE runners
SET backend_handle = $3, updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND state IN ('provisioning', 'running', 'terminating')
RETURNING id, session_id, workspace_id, backend, backend_handle, state, failure_reason, created_at, ready_at, terminated_at, updated_at
`

type SetRunnerHandleParams struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	BackendHandle *string
}

// Recorded as soon as the backend returns one, so a crash after this point
// leaves something to tear down rather than an environment nothing names.
func (q *Queries) SetRunnerHandle(ctx context.Context, arg SetRunnerHandleParams) (Runner, error) {
	row := q.db.QueryRow(ctx, setRunnerHandle, arg.ID, arg.WorkspaceID, arg.BackendHandle)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkspaceID,
		&i.Backend,
		&i.BackendHandle,
		&i.State,
		&i.FailureReason,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.TerminatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
