// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_approvals.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSecretApprovalDecision = `-- name: GetSecretApprovalDecision :one
SELECT id, intent_id, workspace_id, secret_version, version_seconds, version_nanos, schema_version, credential_kind, principal_id, created_at FROM provider_secret_approvals WHERE id=$1 AND workspace_id=$2
`

type GetSecretApprovalDecisionParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetSecretApprovalDecision(ctx context.Context, arg GetSecretApprovalDecisionParams) (ProviderSecretApproval, error) {
	row := q.db.QueryRow(ctx, getSecretApprovalDecision, arg.ID, arg.WorkspaceID)
	var i ProviderSecretApproval
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.WorkspaceID,
		&i.SecretVersion,
		&i.VersionSeconds,
		&i.VersionNanos,
		&i.SchemaVersion,
		&i.CredentialKind,
		&i.PrincipalID,
		&i.CreatedAt,
	)
	return i, err
}

const getSecretAssignment = `-- name: GetSecretAssignment :one
SELECT intent_id, workspace_id, secret_seconds, secret_nanos, principal_id, created_at FROM provider_secret_assignments WHERE intent_id=$1 AND workspace_id=$2
`

type GetSecretAssignmentParams struct {
	IntentID    uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetSecretAssignment(ctx context.Context, arg GetSecretAssignmentParams) (ProviderSecretAssignment, error) {
	row := q.db.QueryRow(ctx, getSecretAssignment, arg.IntentID, arg.WorkspaceID)
	var i ProviderSecretAssignment
	err := row.Scan(
		&i.IntentID,
		&i.WorkspaceID,
		&i.SecretSeconds,
		&i.SecretNanos,
		&i.PrincipalID,
		&i.CreatedAt,
	)
	return i, err
}

const getSecretIntent = `-- name: GetSecretIntent :one
SELECT id, workspace_id, provider, environment, project_number, secret_id, resource_family, initial_version, principal_id, created_at FROM provider_secret_intents WHERE id=$1 AND workspace_id=$2
`

type GetSecretIntentParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetSecretIntent(ctx context.Context, arg GetSecretIntentParams) (ProviderSecretIntent, error) {
	row := q.db.QueryRow(ctx, getSecretIntent, arg.ID, arg.WorkspaceID)
	var i ProviderSecretIntent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.Environment,
		&i.ProjectNumber,
		&i.SecretID,
		&i.ResourceFamily,
		&i.InitialVersion,
		&i.PrincipalID,
		&i.CreatedAt,
	)
	return i, err
}

const getSecretWithdrawal = `-- name: GetSecretWithdrawal :one
SELECT id, intent_id, workspace_id, approval_id, principal_id, created_at FROM provider_secret_withdrawals WHERE id=$1 AND workspace_id=$2
`

type GetSecretWithdrawalParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetSecretWithdrawal(ctx context.Context, arg GetSecretWithdrawalParams) (ProviderSecretWithdrawal, error) {
	row := q.db.QueryRow(ctx, getSecretWithdrawal, arg.ID, arg.WorkspaceID)
	var i ProviderSecretWithdrawal
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.WorkspaceID,
		&i.ApprovalID,
		&i.PrincipalID,
		&i.CreatedAt,
	)
	return i, err
}

const hasInitialSecretApproval = `-- name: HasInitialSecretApproval :one
SELECT EXISTS(SELECT 1 FROM provider_secret_approvals WHERE intent_id=$1 AND workspace_id=$2 AND secret_version=$3)
`

type HasInitialSecretApprovalParams struct {
	IntentID      uuid.UUID
	WorkspaceID   uuid.UUID
	SecretVersion int64
}

func (q *Queries) HasInitialSecretApproval(ctx context.Context, arg HasInitialSecretApprovalParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasInitialSecretApproval, arg.IntentID, arg.WorkspaceID, arg.SecretVersion)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertSecretApproval = `-- name: InsertSecretApproval :exec
INSERT INTO provider_secret_approvals(id,intent_id,workspace_id,secret_version,version_seconds,version_nanos,principal_id)
VALUES($1,$2,$3,$4,$5,$6,$7)
`

type InsertSecretApprovalParams struct {
	ID             uuid.UUID
	IntentID       uuid.UUID
	WorkspaceID    uuid.UUID
	SecretVersion  int64
	VersionSeconds int64
	VersionNanos   int32
	PrincipalID    uuid.UUID
}

func (q *Queries) InsertSecretApproval(ctx context.Context, arg InsertSecretApprovalParams) error {
	_, err := q.db.Exec(ctx, insertSecretApproval,
		arg.ID,
		arg.IntentID,
		arg.WorkspaceID,
		arg.SecretVersion,
		arg.VersionSeconds,
		arg.VersionNanos,
		arg.PrincipalID,
	)
	return err
}

const insertSecretAssignment = `-- name: InsertSecretAssignment :exec
INSERT INTO provider_secret_assignments(intent_id,workspace_id,secret_seconds,secret_nanos,principal_id) VALUES($1,$2,$3,$4,$5)
`

type InsertSecretAssignmentParams struct {
	IntentID      uuid.UUID
	WorkspaceID   uuid.UUID
	SecretSeconds int64
	SecretNanos   int32
	PrincipalID   uuid.UUID
}

func (q *Queries) InsertSecretAssignment(ctx context.Context, arg InsertSecretAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertSecretAssignment,
		arg.IntentID,
		arg.WorkspaceID,
		arg.SecretSeconds,
		arg.SecretNanos,
		arg.PrincipalID,
	)
	return err
}

const insertSecretIntent = `-- name: InsertSecretIntent :exec
INSERT INTO provider_secret_intents(id,workspace_id,provider,environment,project_number,secret_id,initial_version,principal_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertSecretIntentParams struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	Provider       string
	Environment    string
	ProjectNumber  string
	SecretID       uuid.UUID
	InitialVersion int64
	PrincipalID    uuid.UUID
}

func (q *Queries) InsertSecretIntent(ctx context.Context, arg InsertSecretIntentParams) error {
	_, err := q.db.Exec(ctx, insertSecretIntent,
		arg.ID,
		arg.WorkspaceID,
		arg.Provider,
		arg.Environment,
		arg.ProjectNumber,
		arg.SecretID,
		arg.InitialVersion,
		arg.PrincipalID,
	)
	return err
}

const insertSecretReservation = `-- name: InsertSecretReservation :exec
INSERT INTO provider_secret_reservations(project_number,secret_id,environment) VALUES($1,$2,$3)
`

type InsertSecretReservationParams struct {
	ProjectNumber string
	SecretID      uuid.UUID
	Environment   string
}

func (q *Queries) InsertSecretReservation(ctx context.Context, arg InsertSecretReservationParams) error {
	_, err := q.db.Exec(ctx, insertSecretReservation, arg.ProjectNumber, arg.SecretID, arg.Environment)
	return err
}

const insertSecretWithdrawal = `-- name: InsertSecretWithdrawal :exec
INSERT INTO provider_secret_withdrawals(id,intent_id,workspace_id,approval_id,principal_id) VALUES($1,$2,$3,$4,$5)
`

type InsertSecretWithdrawalParams struct {
	ID          uuid.UUID
	IntentID    uuid.UUID
	WorkspaceID uuid.UUID
	ApprovalID  pgtype.UUID
	PrincipalID uuid.UUID
}

func (q *Queries) InsertSecretWithdrawal(ctx context.Context, arg InsertSecretWithdrawalParams) error {
	_, err := q.db.Exec(ctx, insertSecretWithdrawal,
		arg.ID,
		arg.IntentID,
		arg.WorkspaceID,
		arg.ApprovalID,
		arg.PrincipalID,
	)
	return err
}

const lockSecretIntentRoot = `-- name: LockSecretIntentRoot :one
SELECT r.state FROM provider_secret_reservations r
JOIN provider_secret_intents i ON i.project_number=r.project_number AND i.secret_id=r.secret_id
WHERE i.id=$1 AND i.workspace_id=$2 FOR UPDATE OF r
`

type LockSecretIntentRootParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) LockSecretIntentRoot(ctx context.Context, arg LockSecretIntentRootParams) (string, error) {
	row := q.db.QueryRow(ctx, lockSecretIntentRoot, arg.ID, arg.WorkspaceID)
	var state string
	err := row.Scan(&state)
	return state, err
}

const lookupSecretApproval = `-- name: LookupSecretApproval :one
SELECT a.id,a.schema_version,a.credential_kind,a.version_seconds,a.version_nanos,
 i.workspace_id,i.provider,i.environment,i.project_number,i.secret_id,i.resource_family,
 s.secret_seconds,s.secret_nanos
FROM provider_secret_approvals a
JOIN provider_secret_intents i ON i.id=a.intent_id AND i.workspace_id=a.workspace_id
JOIN provider_secret_assignments s ON s.intent_id=a.intent_id AND s.workspace_id=a.workspace_id
WHERE i.workspace_id=$1 AND i.provider=$2 AND i.environment=$3 AND i.project_number=$4 AND i.secret_id=$5
 AND a.secret_version=$6
 AND NOT EXISTS(SELECT 1 FROM provider_secret_withdrawals w WHERE w.intent_id=a.intent_id AND w.workspace_id=a.workspace_id AND (w.approval_id IS NULL OR w.approval_id=a.id))
`

type LookupSecretApprovalParams struct {
	WorkspaceID   uuid.UUID
	Provider      string
	Environment   string
	ProjectNumber string
	SecretID      uuid.UUID
	SecretVersion int64
}

type LookupSecretApprovalRow struct {
	ID             uuid.UUID
	SchemaVersion  int32
	CredentialKind string
	VersionSeconds int64
	VersionNanos   int32
	WorkspaceID    uuid.UUID
	Provider       string
	Environment    string
	ProjectNumber  string
	SecretID       uuid.UUID
	ResourceFamily string
	SecretSeconds  int64
	SecretNanos    int32
}

func (q *Queries) LookupSecretApproval(ctx context.Context, arg LookupSecretApprovalParams) (LookupSecretApprovalRow, error) {
	row := q.db.QueryRow(ctx, lookupSecretApproval,
		arg.WorkspaceID,
		arg.Provider,
		arg.Environment,
		arg.ProjectNumber,
		arg.SecretID,
		arg.SecretVersion,
	)
	var i LookupSecretApprovalRow
	err := row.Scan(
		&i.ID,
		&i.SchemaVersion,
		&i.CredentialKind,
		&i.VersionSeconds,
		&i.VersionNanos,
		&i.WorkspaceID,
		&i.Provider,
		&i.Environment,
		&i.ProjectNumber,
		&i.SecretID,
		&i.ResourceFamily,
		&i.SecretSeconds,
		&i.SecretNanos,
	)
	return i, err
}

const lookupSelectedSecretApproval = `-- name: LookupSelectedSecretApproval :one
SELECT a.id,a.schema_version,a.credential_kind,a.version_seconds,a.version_nanos,
 i.workspace_id,i.provider,i.environment,i.project_number,i.secret_id,i.resource_family,
 s.secret_seconds,s.secret_nanos
FROM provider_secret_approvals a
JOIN provider_secret_intents i ON i.id=a.intent_id AND i.workspace_id=a.workspace_id
JOIN provider_secret_assignments s ON s.intent_id=a.intent_id AND s.workspace_id=a.workspace_id
WHERE a.id=$1 AND i.workspace_id=$2 AND i.provider=$3 AND i.environment=$4 AND i.project_number=$5 AND i.secret_id=$6
 AND a.secret_version=$7
 AND NOT EXISTS(SELECT 1 FROM provider_secret_withdrawals w WHERE w.intent_id=a.intent_id AND w.workspace_id=a.workspace_id AND (w.approval_id IS NULL OR w.approval_id=a.id))
`

type LookupSelectedSecretApprovalParams struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	Provider      string
	Environment   string
	ProjectNumber string
	SecretID      uuid.UUID
	SecretVersion int64
}

type LookupSelectedSecretApprovalRow struct {
	ID             uuid.UUID
	SchemaVersion  int32
	CredentialKind string
	VersionSeconds int64
	VersionNanos   int32
	WorkspaceID    uuid.UUID
	Provider       string
	Environment    string
	ProjectNumber  string
	SecretID       uuid.UUID
	ResourceFamily string
	SecretSeconds  int64
	SecretNanos    int32
}

func (q *Queries) LookupSelectedSecretApproval(ctx context.Context, arg LookupSelectedSecretApprovalParams) (LookupSelectedSecretApprovalRow, error) {
	row := q.db.QueryRow(ctx, lookupSelectedSecretApproval,
		arg.ID,
		arg.WorkspaceID,
		arg.Provider,
		arg.Environment,
		arg.ProjectNumber,
		arg.SecretID,
		arg.SecretVersion,
	)
	var i LookupSelectedSecretApprovalRow
	err := row.Scan(
		&i.ID,
		&i.SchemaVersion,
		&i.CredentialKind,
		&i.VersionSeconds,
		&i.VersionNanos,
		&i.WorkspaceID,
		&i.Provider,
		&i.Environment,
		&i.ProjectNumber,
		&i.SecretID,
		&i.ResourceFamily,
		&i.SecretSeconds,
		&i.SecretNanos,
	)
	return i, err
}
