// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSessionParticipant = `-- name: AddSessionParticipant :one
INSERT INTO session_participants (session_id, workspace_id, user_id, capacity)
VALUES ($1, $2, $3, $4)
RETURNING session_id, workspace_id, user_id, capacity, created_at
`

type AddSessionParticipantParams struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Capacity    string
}

func (q *Queries) AddSessionParticipant(ctx context.Context, arg AddSessionParticipantParams) (SessionParticipant, error) {
	row := q.db.QueryRow(ctx, addSessionParticipant,
		arg.SessionID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Capacity,
	)
	var i SessionParticipant
	err := row.Scan(
		&i.SessionID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Capacity,
		&i.CreatedAt,
	)
	return i, err
}

const appendSessionTransition = `-- name: AppendSessionTransition :one
INSERT INTO session_state_transitions (
    id, session_id, workspace_id, previous_state, next_state,
    observed_version, reason, actor_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, session_id, workspace_id, previous_state, next_state, observed_version, reason, actor_user_id, created_at
`

type AppendSessionTransitionParams struct {
	ID              uuid.UUID
	SessionID       uuid.UUID
	WorkspaceID     uuid.UUID
	PreviousState   *string
	NextState       string
	ObservedVersion int32
	Reason          string
	ActorUserID     pgtype.UUID
}

// Append-only, enforced by trigger as well as by there being no other
// statement that touches this table.
func (q *Queries) AppendSessionTransition(ctx context.Context, arg AppendSessionTransitionParams) (SessionStateTransition, error) {
	row := q.db.QueryRow(ctx, appendSessionTransition,
		arg.ID,
		arg.SessionID,
		arg.WorkspaceID,
		arg.PreviousState,
		arg.NextState,
		arg.ObservedVersion,
		arg.Reason,
		arg.ActorUserID,
	)
	var i SessionStateTransition
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkspaceID,
		&i.PreviousState,
		&i.NextState,
		&i.ObservedVersion,
		&i.Reason,
		&i.ActorUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, workspace_id, task_id, agent_version_id, state,
    repository_id, branch_name, base_branch, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, task_id, agent_version_id, state, version, repository_id, branch_name, base_branch, continues_id, created_by, created_at, updated_at
`

type CreateSessionParams struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	TaskID         uuid.UUID
	AgentVersionID uuid.UUID
	State          string
	RepositoryID   uuid.UUID
	BranchName     string
	BaseBranch     string
	CreatedBy      uuid.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.WorkspaceID,
		arg.TaskID,
		arg.AgentVersionID,
		arg.State,
		arg.RepositoryID,
		arg.BranchName,
		arg.BaseBranch,
		arg.CreatedBy,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.AgentVersionID,
		&i.State,
		&i.Version,
		&i.RepositoryID,
		&i.BranchName,
		&i.BaseBranch,
		&i.ContinuesID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueOutboxEvent = `-- name: EnqueueOutboxEvent :one
INSERT INTO outbox_events (id, workspace_id, topic, subject_id, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, topic, subject_id, payload, attempts, available_at, leased_until, last_error, completed_at, created_at
`

type EnqueueOutboxEventParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Topic       string
	SubjectID   uuid.UUID
	Payload     []byte
}

// Written in the same transaction as the thing it promises. That is the whole
// mechanism: writing the session and then publishing leaves a window where the
// session exists and nothing will pick it up, open exactly when the process
// dies.
func (q *Queries) EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, enqueueOutboxEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.Topic,
		arg.SubjectID,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Topic,
		&i.SubjectID,
		&i.Payload,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeasedUntil,
		&i.LastError,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionForWorkspace = `-- name: GetSessionForWorkspace :one
SELECT id, workspace_id, task_id, agent_version_id, state, version, repository_id, branch_name, base_branch, continues_id, created_by, created_at, updated_at FROM sessions
WHERE id = $1 AND workspace_id = $2
`

type GetSessionForWorkspaceParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Scoped by workspace, so a session id from one tenant cannot be read through
// another even before the policies are consulted.
func (q *Queries) GetSessionForWorkspace(ctx context.Context, arg GetSessionForWorkspaceParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionForWorkspace, arg.ID, arg.WorkspaceID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.AgentVersionID,
		&i.State,
		&i.Version,
		&i.RepositoryID,
		&i.BranchName,
		&i.BaseBranch,
		&i.ContinuesID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT id, workspace_id, topic, subject_id, payload, attempts, available_at, leased_until, last_error, completed_at, created_at FROM outbox_events
WHERE workspace_id = $1
  AND completed_at IS NULL
  AND available_at <= now()
  AND (leased_until IS NULL OR leased_until < now())
ORDER BY available_at, id
`

// Reads what a claimer would find, without claiming it.
//
// `leased_until` is a lease and not a flag: a row whose lease has expired is
// pending again, because the publisher holding it died and no operator is
// going to notice a boolean nobody will ever clear. The claim itself lands in
// M5 as a single conditional UPDATE, so that two claimers cannot both win.
func (q *Queries) ListPendingOutboxEvents(ctx context.Context, workspaceID uuid.UUID) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEvents, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Topic,
			&i.SubjectID,
			&i.Payload,
			&i.Attempts,
			&i.AvailableAt,
			&i.LeasedUntil,
			&i.LastError,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionParticipants = `-- name: ListSessionParticipants :many
SELECT session_id, workspace_id, user_id, capacity, created_at FROM session_participants
WHERE session_id = $1 AND workspace_id = $2
ORDER BY created_at
`

type ListSessionParticipantsParams struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) ListSessionParticipants(ctx context.Context, arg ListSessionParticipantsParams) ([]SessionParticipant, error) {
	rows, err := q.db.Query(ctx, listSessionParticipants, arg.SessionID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionParticipant{}
	for rows.Next() {
		var i SessionParticipant
		if err := rows.Scan(
			&i.SessionID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Capacity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionTransitions = `-- name: ListSessionTransitions :many
SELECT id, session_id, workspace_id, previous_state, next_state, observed_version, reason, actor_user_id, created_at FROM session_state_transitions
WHERE session_id = $1 AND workspace_id = $2
ORDER BY created_at, id
`

type ListSessionTransitionsParams struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) ListSessionTransitions(ctx context.Context, arg ListSessionTransitionsParams) ([]SessionStateTransition, error) {
	rows, err := q.db.Query(ctx, listSessionTransitions, arg.SessionID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionStateTransition{}
	for rows.Next() {
		var i SessionStateTransition
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.WorkspaceID,
			&i.PreviousState,
			&i.NextState,
			&i.ObservedVersion,
			&i.Reason,
			&i.ActorUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForWorkspace = `-- name: ListSessionsForWorkspace :many
SELECT id, workspace_id, task_id, agent_version_id, state, version, repository_id, branch_name, base_branch, continues_id, created_by, created_at, updated_at FROM sessions
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TaskID,
			&i.AgentVersionID,
			&i.State,
			&i.Version,
			&i.RepositoryID,
			&i.BranchName,
			&i.BaseBranch,
			&i.ContinuesID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSessionForUpdate = `-- name: LockSessionForUpdate :one
SELECT id, workspace_id, task_id, agent_version_id, state, version, repository_id, branch_name, base_branch, continues_id, created_by, created_at, updated_at FROM sessions
WHERE id = $1 AND workspace_id = $2
FOR UPDATE
`

type LockSessionForUpdateParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Taken before a state change. The version read here is the one the change is
// checked against, and holding the lock is what stops two transitions reading
// the same version and both believing they are current.
func (q *Queries) LockSessionForUpdate(ctx context.Context, arg LockSessionForUpdateParams) (Session, error) {
	row := q.db.QueryRow(ctx, lockSessionForUpdate, arg.ID, arg.WorkspaceID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.AgentVersionID,
		&i.State,
		&i.Version,
		&i.RepositoryID,
		&i.BranchName,
		&i.BaseBranch,
		&i.ContinuesID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionState = `-- name: UpdateSessionState :one
UPDATE sessions
SET state      = $3,
    version    = version + 1,
    updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND version = $4
RETURNING id, workspace_id, task_id, agent_version_id, state, version, repository_id, branch_name, base_branch, continues_id, created_by, created_at, updated_at
`

type UpdateSessionStateParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	State       string
	Version     int32
}

// The version predicate is belt-and-braces behind LockSessionForUpdate: the
// lock already serialises writers, and this refuses to write at all if the row
// moved between the two — which is the thing that must never silently happen.
func (q *Queries) UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionState,
		arg.ID,
		arg.WorkspaceID,
		arg.State,
		arg.Version,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.AgentVersionID,
		&i.State,
		&i.Version,
		&i.RepositoryID,
		&i.BranchName,
		&i.BaseBranch,
		&i.ContinuesID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
