// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, workspace_id, repository_id, title, body, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, repository_id, title, body, status, created_by, created_at, updated_at
`

type CreateTaskParams struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	RepositoryID pgtype.UUID
	Title        string
	Body         string
	Status       string
	CreatedBy    uuid.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.WorkspaceID,
		arg.RepositoryID,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepositoryID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskForWorkspace = `-- name: GetTaskForWorkspace :one
SELECT id, workspace_id, repository_id, title, body, status, created_by, created_at, updated_at FROM tasks
WHERE id = $1 AND workspace_id = $2
`

type GetTaskForWorkspaceParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Scoped by workspace, so a task id from one tenant cannot be read through
// another even before the policies are consulted.
func (q *Queries) GetTaskForWorkspace(ctx context.Context, arg GetTaskForWorkspaceParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForWorkspace, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepositoryID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksForWorkspace = `-- name: ListTasksForWorkspace :many
SELECT id, workspace_id, repository_id, title, body, status, created_by, created_at, updated_at FROM tasks
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RepositoryID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskForUpdate = `-- name: LockTaskForUpdate :one
SELECT id, workspace_id, repository_id, title, body, status, created_by, created_at, updated_at FROM tasks
WHERE id = $1 AND workspace_id = $2
FOR UPDATE
`

type LockTaskForUpdateParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Read at the start of a patch, in the transaction that writes it.
//
// What makes a patch safe is that the read happens here rather than in an
// earlier transaction: a read-modify-write split across two transactions lets
// two concurrent edits to different fields both read the same row, the second
// writing its own field alongside stale copies of the rest and silently
// undoing the first. That was measured — reproducing the split shape fails the
// concurrency test every run.
//
// FOR UPDATE is not what prevents it today. authorizeActor takes LockWorkspace
// before this runs, which already serializes every mutation in a workspace, so
// this narrower lock is redundant in the current arrangement — the same
// relationship LockAgentForUpdate has. It is here so this transaction states
// the row it depends on rather than relying on the workspace lock staying as
// coarse as it is.
func (q *Queries) LockTaskForUpdate(ctx context.Context, arg LockTaskForUpdateParams) (Task, error) {
	row := q.db.QueryRow(ctx, lockTaskForUpdate, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepositoryID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET repository_id = $3,
    title         = $4,
    body          = $5,
    status        = $6,
    updated_at    = now()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, repository_id, title, body, status, created_by, created_at, updated_at
`

type UpdateTaskParams struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	RepositoryID pgtype.UUID
	Title        string
	Body         string
	Status       string
}

// The body is written back exactly as given. Nothing here normalises it: the
// stored value and the returned value must agree, or nobody can tell what is
// actually stored.
func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.WorkspaceID,
		arg.RepositoryID,
		arg.Title,
		arg.Body,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepositoryID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
