// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

// Test and operator support only; not used on a request path.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, external_id, email, display_name, avatar_url, created_at, updated_at FROM users
WHERE external_id = $1
`

func (q *Queries) GetUserByExternalID(ctx context.Context, externalID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalID, externalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByExternalID = `-- name: UpsertUserByExternalID :one
INSERT INTO users (id, external_id, email, display_name, avatar_url)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (external_id) DO UPDATE
SET email        = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    avatar_url   = EXCLUDED.avatar_url,
    updated_at   = now()
RETURNING id, external_id, email, display_name, avatar_url, created_at, updated_at
`

type UpsertUserByExternalIDParams struct {
	ID          uuid.UUID
	ExternalID  string
	Email       string
	DisplayName *string
	AvatarUrl   *string
}

// Just-in-time provisioning. ON CONFLICT makes concurrent first requests for
// the same subject resolve to a single row instead of racing, and DO UPDATE
// (rather than DO NOTHING) guarantees RETURNING yields the row either way.
func (q *Queries) UpsertUserByExternalID(ctx context.Context, arg UpsertUserByExternalIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByExternalID,
		arg.ID,
		arg.ExternalID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
