// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package postgresdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :one
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING workspace_id, user_id, role, created_at, updated_at
`

type AddWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const appendAuditEvent = `-- name: AppendAuditEvent :one
INSERT INTO audit_events (id, workspace_id, actor_user_id, action, target, detail)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, actor_user_id, action, target, detail, occurred_at
`

type AppendAuditEventParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ActorUserID pgtype.UUID
	Action      string
	Target      *string
	Detail      []byte
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, appendAuditEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.ActorUserID,
		arg.Action,
		arg.Target,
		arg.Detail,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActorUserID,
		&i.Action,
		&i.Target,
		&i.Detail,
		&i.OccurredAt,
	)
	return i, err
}

const countWorkspaceOwners = `-- name: CountWorkspaceOwners :one
SELECT count(*) FROM workspace_members
WHERE workspace_id = $1 AND role = 'owner'
`

// Used under LockWorkspace to enforce that a workspace never loses its last
// owner.
func (q *Queries) CountWorkspaceOwners(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceOwners, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, slug, name, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, created_by, version, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedBy uuid.UUID
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.CreatedBy,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :execrows
DELETE FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceForMember = `-- name: GetWorkspaceForMember :one
SELECT w.id, w.slug, w.name, w.created_by, w.version, w.created_at, w.updated_at
FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE w.id = $1 AND m.user_id = $2
`

type GetWorkspaceForMemberParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Scoped by member, not just by id. A caller who is not a member gets no row,
// so "not found" and "not yours" are indistinguishable from the outside and
// workspace identifiers cannot be probed.
func (q *Queries) GetWorkspaceForMember(ctx context.Context, arg GetWorkspaceForMemberParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForMember, arg.ID, arg.UserID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT workspace_id, user_id, role, created_at, updated_at FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, workspace_id, actor_user_id, action, target, detail, occurred_at FROM audit_events
WHERE workspace_id = $1
ORDER BY occurred_at DESC, id
LIMIT $2
`

type ListAuditEventsParams struct {
	WorkspaceID uuid.UUID
	Limit       int32
}

// Operator and test support.
func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorUserID,
			&i.Action,
			&i.Target,
			&i.Detail,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT m.workspace_id, m.user_id, m.role, m.created_at, m.updated_at,
       u.email, u.display_name, u.avatar_url
FROM workspace_members m
JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1
ORDER BY m.created_at
`

type ListWorkspaceMembersRow struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Email       string
	DisplayName *string
	AvatarUrl   *string
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.slug, w.name, w.created_by, w.version, w.created_at, w.updated_at, m.role
FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE m.user_id = $1
ORDER BY w.created_at
`

type ListWorkspacesForUserRow struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedBy uuid.UUID
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Role      string
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspace = `-- name: LockWorkspace :one
SELECT id FROM workspaces WHERE id = $1 FOR UPDATE
`

// Serialises membership changes within a workspace. Taken before any check
// that counts owners, so two concurrent demotions cannot both observe two
// owners and both proceed.
func (q *Queries) LockWorkspace(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockWorkspace, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const renameWorkspace = `-- name: RenameWorkspace :one
UPDATE workspaces
SET name = $3,
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND version = $2
RETURNING id, slug, name, created_by, version, created_at, updated_at
`

type RenameWorkspaceParams struct {
	ID      uuid.UUID
	Version int32
	Name    string
}

// Optimistic concurrency: the caller supplies the version it read. A stale
// version matches no row, which the store reports as a conflict rather than
// silently overwriting a concurrent edit.
func (q *Queries) RenameWorkspace(ctx context.Context, arg RenameWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, renameWorkspace, arg.ID, arg.Version, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS (SELECT 1 FROM workspaces WHERE slug = $1)
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :one
UPDATE workspace_members
SET role = $3, updated_at = now()
WHERE workspace_id = $1 AND user_id = $2
RETURNING workspace_id, user_id, role, created_at, updated_at
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
