-- +goose Up
-- +goose StatementBegin

-- citext gives case-insensitive email comparison without scattering lower()
-- through every query.
CREATE EXTENSION IF NOT EXISTS citext;

-- Application users.
--
-- `id` is the only identifier the product ever uses. `external_id` is the
-- identity-provider subject (today Clerk) and is deliberately a plain unique
-- column, never a primary or foreign key: swapping identity providers, or
-- re-linking an account, must not require rewriting every referencing row.
CREATE TABLE users (
    -- UUIDv7 generated by the application. PostgreSQL 17 has no uuidv7()
    -- built in, and architecture.md specifies application-generated keys.
    id            uuid PRIMARY KEY,
    external_id   text        NOT NULL,
    email         citext      NOT NULL,
    display_name  text,
    avatar_url    text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT users_external_id_key UNIQUE (external_id),
    CONSTRAINT users_external_id_not_blank CHECK (length(btrim(external_id)) > 0),
    CONSTRAINT users_email_not_blank CHECK (length(btrim(email::text)) > 0)
);

-- The unique constraint above is what makes just-in-time provisioning safe:
-- concurrent first requests for the same subject resolve to one row through
-- INSERT ... ON CONFLICT rather than racing.

COMMENT ON TABLE users IS 'Application users. One row per identity-provider subject.';
COMMENT ON COLUMN users.external_id IS 'Identity-provider subject (Clerk). Never used as a primary or foreign key.';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE users;

-- citext is intentionally left installed: other tables may already depend on
-- it, and dropping an extension is not reversible in the way a table is.

-- +goose StatementEnd
