-- +goose Up
-- +goose StatementBegin

-- Runners (Unit M5.4a): the execution environments sessions run in.
--
-- A runner is the first thing in Weave that executes what Weave did not write.
-- This table is how the control plane knows which environment belongs to which
-- session — and therefore which producer may write which session's history.
-- M5.3 handed exactly that gap to this unit: until a runner was bound to its
-- session, anything able to publish could write history for any session whose
-- id it knew.

CREATE TABLE runners (
    -- Generated by the control plane and handed to the runner. A runner never
    -- chooses its own id: the id is what binds its events to its session.
    id              uuid        PRIMARY KEY,
    session_id      uuid        NOT NULL,
    workspace_id    uuid        NOT NULL,
    -- Which RunnerBackend created it, and that backend's own handle for it
    -- (a container id for the dev backend, a sandbox id for a vendor's).
    backend         text        NOT NULL,
    backend_handle  text,
    state           text        NOT NULL DEFAULT 'provisioning',
    -- Why it ended, when it ended other than by an ordinary teardown. Our own
    -- words, never output from the runner.
    failure_reason  text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    ready_at        timestamptz,
    terminated_at   timestamptz,
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT runners_session_fkey
        FOREIGN KEY (session_id, workspace_id)
        REFERENCES sessions (id, workspace_id) ON DELETE CASCADE,
    CONSTRAINT runners_state_valid CHECK (state IN (
        'provisioning', 'running', 'terminating', 'terminated', 'failed'
    )),
    CONSTRAINT runners_backend_valid CHECK (backend ~ '^[a-z][a-z0-9-]{0,31}$'),
    CONSTRAINT runners_backend_handle_length CHECK (backend_handle IS NULL OR length(backend_handle) <= 256),
    CONSTRAINT runners_failure_reason_length CHECK (failure_reason IS NULL OR length(failure_reason) <= 500),
    -- A runner that has ended says when.
    CONSTRAINT runners_ended_has_time CHECK (
        (state IN ('terminated', 'failed')) = (terminated_at IS NOT NULL)
    )
);

-- One live runner per session, enforced here rather than by a check first: a
-- redelivered provisioning activity must find the runner it already started,
-- and this is the backstop that makes a second one impossible even if it does
-- not. `failed` and `terminated` runners are history and do not count.
CREATE UNIQUE INDEX runners_one_live_per_session
    ON runners (session_id)
    WHERE state IN ('provisioning', 'running', 'terminating');

CREATE INDEX runners_workspace_idx ON runners (workspace_id);
CREATE INDEX runners_live_idx ON runners (state) WHERE state IN ('provisioning', 'running', 'terminating');

-- --------------------------------------------------------------------------
-- Finding runners to reconcile
--
-- The runner manager reconciles across every workspace — at startup, to find
-- runners a crash left behind, and periodically, to tear down runners whose
-- session has ended or whose environment has vanished. It has no tenant, and
-- under FORCE RLS a direct read matches nothing while reporting success.
--
-- So this one read is privileged, and bounded the way M5.0, M5.1 and M5.3
-- learned to bound them: live runners only, capped, no filter taken from the
-- caller beyond the cap. Each runner it returns carries its own workspace, and
-- every write that follows runs in a tenant transaction scoped by **that**.
-- --------------------------------------------------------------------------
CREATE FUNCTION weave_runners_to_reconcile(batch_size integer)
RETURNS TABLE (
    id uuid, session_id uuid, workspace_id uuid, backend text,
    backend_handle text, state text, session_state text, created_at timestamptz
)
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF batch_size IS NULL OR batch_size < 1 OR batch_size > 500 THEN
        RAISE EXCEPTION 'runner reconcile batch size must be between 1 and 500, got %', batch_size
            USING ERRCODE = 'invalid_parameter_value';
    END IF;

    RETURN QUERY
    SELECT r.id, r.session_id, r.workspace_id, r.backend, r.backend_handle,
           r.state, s.state, r.created_at
    FROM runners r
    JOIN sessions s ON s.id = r.session_id
    WHERE r.state IN ('provisioning', 'running', 'terminating')
    ORDER BY r.created_at
    LIMIT batch_size;
END;
$$;

ALTER FUNCTION weave_runners_to_reconcile(integer) OWNER TO weave_rls_bypass;
GRANT SELECT ON runners TO weave_rls_bypass;
REVOKE ALL ON FUNCTION weave_runners_to_reconcile(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION weave_runners_to_reconcile(integer) TO weave_app;

-- --------------------------------------------------------------------------
-- The quarantine learns a reason: an event from a runner not bound to its
-- session, or one already ended.
-- --------------------------------------------------------------------------
ALTER TABLE session_event_quarantine DROP CONSTRAINT session_event_quarantine_reason_known;
ALTER TABLE session_event_quarantine ADD CONSTRAINT session_event_quarantine_reason_known CHECK (reason IN (
    'malformed', 'oversize', 'unknown_major_version', 'unknown_type',
    'invalid_payload', 'subject_mismatch', 'workspace_mismatch',
    'unknown_session', 'session_terminal', 'delivery_exhausted',
    'unparseable_subject', 'runner_not_bound'
));

-- --------------------------------------------------------------------------
-- Grants and policies
-- --------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON runners TO weave_app;

ALTER TABLE runners ENABLE ROW LEVEL SECURITY;
ALTER TABLE runners FORCE  ROW LEVEL SECURITY;

CREATE POLICY runners_tenant_read ON runners FOR SELECT
    USING (workspace_id = weave_current_workspace_id());
CREATE POLICY runners_tenant_insert ON runners FOR INSERT
    WITH CHECK (workspace_id = weave_current_workspace_id());
CREATE POLICY runners_tenant_update ON runners FOR UPDATE
    USING (workspace_id = weave_current_workspace_id())
    WITH CHECK (workspace_id = weave_current_workspace_id());

COMMENT ON TABLE runners IS 'Execution environments, one live per session. The id binds a runner''s events to its session.';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- Rows carrying the reason this migration added would violate the older
-- constraint. Quarantine rows are operator diagnostics, not history.
DELETE FROM session_event_quarantine WHERE reason = 'runner_not_bound';
ALTER TABLE session_event_quarantine DROP CONSTRAINT session_event_quarantine_reason_known;
ALTER TABLE session_event_quarantine ADD CONSTRAINT session_event_quarantine_reason_known CHECK (reason IN (
    'malformed', 'oversize', 'unknown_major_version', 'unknown_type',
    'invalid_payload', 'subject_mismatch', 'workspace_mismatch',
    'unknown_session', 'session_terminal', 'delivery_exhausted',
    'unparseable_subject'
));
DROP FUNCTION IF EXISTS weave_runners_to_reconcile(integer);
DROP TABLE IF EXISTS runners;

-- +goose StatementEnd
