//go:build vercel_live

package vercelsandbox

import (
	"context"
	"strings"
	"testing"

	"github.com/google/uuid"

	"github.com/jigmetnamgyal/weave/internal/application"
)

// TestLiveDeniedRangesOverrideAllowedHosts verifies the enforcement primitive
// needed by M5.4d. A real public destination first works under a hostname rule,
// then cannot be reached under the same rule with its address family denied.
// This is not a DNS-rebinding test: that needs controlled DNS and a reachable
// forbidden-address fixture. Keep this distinction in the verification record.
func TestLiveDeniedRangesOverrideAllowedHosts(t *testing.T) {
	b := liveBackend(t, "live"+uuid.NewString()[:6], DefaultLease)
	ctx := context.Background()
	for _, c := range []struct {
		name string
		deny []string
		want bool
	}{
		{"hostname only", nil, true},
		{"hostname with IPv4 denied", []string{"0.0.0.0/0"}, false},
	} {
		t.Run(c.name, func(t *testing.T) {
			id := uuid.New()
			policy := map[string]any{"allow": map[string]any{"github.com": []any{}}}
			if c.deny != nil {
				policy["subnets"] = map[string]any{"deny": c.deny}
			}
			created, err := b.create(ctx, b.sandboxName(id), application.RunnerSpec{RunnerID: id, SessionID: uuid.New()}, policy)
			if err != nil {
				t.Fatalf("create with denied ranges: %v", err)
			}
			t.Cleanup(func() { destroyAndConfirm(t, b, id) })
			// Require GitHub's response, not merely a connection or an error
			// generated by the firewall. No token is sent by this request.
			exit, out, err := b.LiveRun(ctx, created.Sandbox.CurrentSessionID,
				`curl -4 -sS --max-time 15 -D - -o /dev/null https://github.com 2>/dev/null`)
			if err != nil {
				t.Fatal(err)
			}
			reached := exit == 0 && strings.Contains(strings.ToLower(out), "server: github.com")
			t.Logf("GitHub reached=%v, curl exit=%d", reached, exit)
			if reached != c.want {
				t.Fatalf("GitHub reached=%v; want %v", reached, c.want)
			}
		})
	}
}
