/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the authenticated user
         * @description Resolves the presented session token to the caller's Weave user.
         *
         *     On first sign-in the user record is created, so a client never has to
         *     register a user before calling this.
         *
         *     The response carries the internal user identifier only. The identity
         *     provider's subject is never exposed: it is an implementation detail of
         *     how someone signed in, and clients must not key on it.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's workspaces */
        get: operations["listWorkspaces"];
        put?: never;
        /**
         * Create a workspace
         * @description The caller becomes its owner. A workspace always has at least one owner.
         */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** Return one workspace */
        get: operations["getWorkspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename a workspace
         * @description Requires `workspace:manage`.
         *
         *     `version` is mandatory and must be the value from the last read. A
         *     stale version returns `409` rather than overwriting a concurrent edit.
         */
        patch: operations["renameWorkspace"];
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /**
         * List a workspace's invitations
         * @description Requires `member:invite`. Never returns tokens or token hashes.
         *
         *     Omitting `status` returns every invitation. An unrecognised value is
         *     rejected rather than ignored, so a caller never receives the full list
         *     under a filter it believes was applied.
         */
        get: operations["listWorkspaceInvitations"];
        put?: never;
        /**
         * Invite someone to the workspace
         * @description Requires `member:invite`, and the inviter must be able to grant the
         *     role — an admin cannot invite an owner, for the same reason an admin
         *     cannot promote one.
         *
         *     **The response carries the token, and it is the only time it ever
         *     exists outside the recipient's link.** Only its hash is stored, so it
         *     cannot be retrieved afterwards. Surface it immediately or it is lost.
         */
        post: operations["issueWorkspaceInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                invitationId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Withdraw an invitation
         * @description Requires `member:invite`. Only an outstanding invitation can be revoked.
         */
        delete: operations["revokeWorkspaceInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invitations/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Describe an invitation to its holder
         * @description Lets someone see what they are being asked to join before accepting.
         *
         *     `POST` rather than `GET` because the token travels in the body: a
         *     token in a query string ends up in server logs, proxy logs and
         *     `Referer` headers.
         */
        post: operations["previewInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an invitation
         * @description Requires authentication, but not membership — the caller is not a
         *     member yet, and the token is what authorizes them.
         *
         *     The signed-in account's email must match the invited address. A link
         *     that admits whoever opens it would turn a forwarded message into a
         *     workspace breach.
         *
         *     The token is single use: concurrent accepts of one token produce
         *     exactly one membership.
         */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** List a workspace's members */
        get: operations["listWorkspaceMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member
         * @description Requires `member:manage`, except when removing yourself, which any
         *     member may do. Removing the last owner returns `409`.
         */
        delete: operations["removeWorkspaceMember"];
        options?: never;
        head?: never;
        /**
         * Change a member's role
         * @description Requires `member:manage`. Demoting the last owner returns `409`: a
         *     workspace with no owner cannot be administered by anyone.
         */
        patch: operations["changeWorkspaceMemberRole"];
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/github/install": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start connecting a GitHub account to this workspace
         * @description Returns the URL to send the browser to. The server records which
         *     workspace the resulting installation belongs to before answering,
         *     keyed by a single-use value carried in that URL.
         *
         *     That recording is the whole mechanism: GitHub returns an installation
         *     id and nothing identifying the workspace, so the workspace must not be
         *     taken from the callback.
         */
        post: operations["beginGitHubInstall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/github/installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish connecting a GitHub account
         * @description Authenticated but not workspace-scoped: the workspace comes from the
         *     state recorded before the redirect, never from the request.
         *
         *     The same endpoint serves a repository-access change, because GitHub
         *     sends the browser back through it with the installation id it already
         *     has. A collision whose workspace matches the recorded state is an
         *     update and reconciles; one that differs is refused.
         */
        post: operations["completeGitHubInstall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/github/installations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /**
         * List the GitHub accounts connected to this workspace
         * @description Removed installations are excluded. Their repository rows survive for
         *     audit, but the connection is gone.
         */
        get: operations["listGitHubInstallations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/github/installations/{installationId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        /**
         * Report whether an installation can still do its job
         * @description Reports rather than fails. Someone debugging a broken workspace needs
         *     to know which of several things is wrong, and an error response would
         *     collapse them into one.
         *
         *     When GitHub is unreachable this falls back to the permissions recorded
         *     at the last reconciliation, and says so through `reachable`.
         */
        get: operations["getGitHubInstallationHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/github/installations/{installationId}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace the recorded repository set with what GitHub grants now */
        post: operations["reconcileGitHubInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /**
         * List the repositories connected to this workspace
         * @description Withdrawn repositories are included with `granted: false`, so the
         *     interface can say access was removed rather than silently dropping
         *     something a member used yesterday. Repositories belonging to a removed
         *     installation are excluded: their rows are kept for audit, but they are
         *     no longer current state.
         */
        get: operations["listWorkspaceRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/repositories/{repositoryId}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                repositoryId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a branch in a connected repository
         * @description The first external side effect Weave performs on a customer's
         *     repository.
         *
         *     Access is re-checked against GitHub before writing, not against our
         *     records: a grant withdrawn since the page loaded stops the write here.
         *     A protected target is refused outright — protected branches never
         *     receive direct agent writes — though creating a branch *from* a
         *     protected base is normal.
         *
         *     Idempotent by name. A request repeating one that succeeded returns the
         *     same branch with `200` and `created: false`, rather than failing on
         *     GitHub's duplicate-ref refusal. A branch of that name pointing
         *     somewhere other than the requested base is a conflict, not a success.
         */
        post: operations["createBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/github/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive a delivery from GitHub
         * @description Public: GitHub cannot present a session token, so the HMAC signature
         *     over the raw body is the authentication. It is verified before the
         *     payload is parsed.
         *
         *     Rejections carry no body. The sender has no interface to show an error
         *     in, and explaining why a forgery failed only helps the next one.
         */
        post: operations["receiveGitHubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Branch: {
            name: string;
            /** @description The commit the branch points at. */
            sha: string;
            base: string;
            /**
             * @description False when the branch already existed at the requested base.
             *     Reported rather than hidden: the caller has a branch at the commit
             *     they asked for either way, but "already there" and "just made" are
             *     different facts.
             */
            created: boolean;
        };
        Installation: {
            /** Format: uuid */
            id: string;
            account_login: string;
            /** @enum {string} */
            account_type: "User" | "Organization";
            /**
             * @description `all` grants repositories created later too, with no event naming
             *     them — one reason access is reconciled before use.
             * @enum {string}
             */
            repository_selection: "all" | "selected";
            suspended: boolean;
            /** Format: date-time */
            suspended_at?: string;
            /** Format: date-time */
            created_at: string;
        };
        Repository: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Which connected account this came from. A workspace may have
             *     several, and presenting them as one flat list hides which
             *     connection is failing when one of them is.
             */
            installation_id: string;
            owner: string;
            name: string;
            full_name: string;
            default_branch: string;
            private: boolean;
            /**
             * @description False for a repository the installation no longer reaches.
             *     Reported rather than filtered out.
             */
            granted: boolean;
        };
        InstallationHealth: {
            /** Format: uuid */
            installation_id: string;
            account_login: string;
            /** @description False when GitHub could not be reached; the rest is then last-known. */
            reachable: boolean;
            suspended: boolean;
            /**
             * @description Named as `permission:access`, because the only useful thing to tell
             *     someone whose workspace stopped working is which permission to
             *     approve.
             */
            missing_permissions: string[];
            granted_repositories: number;
            error?: string;
        };
        /**
         * @description A member's position in a workspace. Permissions are derived from the
         *     role by the server; clients read `permissions` rather than mapping
         *     roles themselves.
         * @enum {string}
         */
        Role: "owner" | "admin" | "developer" | "viewer";
        /**
         * @description An action a member may perform, named for the action rather than the role.
         * @enum {string}
         */
        Permission: "workspace:read" | "workspace:manage" | "member:invite" | "member:manage" | "session:create" | "session:control" | "action:approve" | "repository:manage" | "billing:manage";
        Workspace: {
            /** Format: uuid */
            id: string;
            /** @description URL-safe identifier, derived from the name and unique across workspaces. */
            slug: string;
            name: string;
            /**
             * @description Optimistic concurrency token. Send it back on the next update; a
             *     stale value is rejected with `409` instead of overwriting.
             */
            version: number;
            role: components["schemas"]["Role"];
            /**
             * @description What the caller may do here. Advisory, for hiding controls the
             *     caller cannot use — the server enforces the same matrix regardless.
             */
            permissions: components["schemas"]["Permission"][];
            /** Format: date-time */
            created_at: string;
        };
        /** @description An offer to join a workspace. Never carries the token or its hash. */
        Invitation: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /**
             * @description Derived from the invitation's timestamps rather than stored, so it
             *     cannot disagree with them. A terminal state wins over expiry: an
             *     invitation accepted while still valid reads as `accepted`.
             * @enum {string}
             */
            status: "pending" | "accepted" | "revoked" | "expired";
            /** Format: email */
            invited_by_email?: string;
            invited_by_display_name?: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            created_at: string;
        };
        IssuedInvitation: components["schemas"]["Invitation"] & {
            /**
             * @description **Shown once.** Only a SHA-256 hash is stored, so this value
             *     cannot be recovered afterwards — not by this API, and not by
             *     anyone with database access. Put it in the invitation link
             *     immediately.
             */
            token: string;
        };
        InvitationTokenRequest: {
            token: string;
        };
        /**
         * @description Deliberately narrow. It tells the holder what they are joining and who
         *     asked, and reveals nothing else about the workspace or its members.
         *
         *     In particular it does **not** include the invited address. A token can
         *     be forwarded, and whoever ends up holding it should not learn who it
         *     was meant for.
         */
        InvitationPreview: {
            workspace_name: string;
            role: components["schemas"]["Role"];
            /** Format: email */
            invited_by_email: string;
            invited_by_display_name?: string;
            /** Format: date-time */
            expires_at: string;
        };
        Member: {
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email: string;
            display_name?: string;
            /** Format: uri */
            avatar_url?: string;
            role: components["schemas"]["Role"];
        };
        User: {
            /**
             * Format: uuid
             * @description The user's Weave identifier. Stable, and the only user identifier the API accepts or returns.
             * @example 0199a3b4-1c2d-7e3f-8a9b-0c1d2e3f4a5b
             */
            id: string;
            /**
             * Format: email
             * @example developer@example.com
             */
            email: string;
            /**
             * @description Omitted when the identity provider supplied no name.
             * @example Ada Lovelace
             */
            display_name?: string;
            /**
             * Format: uri
             * @description Omitted when the identity provider supplied no avatar.
             */
            avatar_url?: string;
        };
        /**
         * @description The error shape returned by every failing endpoint.
         *
         *     It never contains a stack trace, database error, provider response or
         *     internal hostname. Quote `request_id` when reporting a problem: it
         *     correlates to the server-side logs that hold the diagnosis.
         */
        Error: {
            /**
             * @description Stable, machine-readable identifier. Clients branch on this rather than on `message`.
             * @enum {string}
             */
            code: "unauthenticated" | "permission_denied" | "not_found" | "conflict" | "invalid_request" | "internal_error";
            /** @description Human-readable summary, safe to surface to an end user. */
            message: string;
            /** @description Correlates this response with server-side logs. Also returned in the `X-Request-Id` header. */
            request_id: string;
        };
    };
    responses: {
        /**
         * @description No valid credential was presented.
         *
         *     Returned identically whether the token was absent, malformed, expired,
         *     signed by the wrong key, or issued for a different audience.
         *     Distinguishing them would tell a caller how close a forgery attempt
         *     came, and no legitimate client needs the difference.
         */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "unauthenticated",
                 *       "message": "Authentication required. Present a valid bearer token.",
                 *       "request_id": "0199a3b4-1c2d-7e3f-8a9b-0c1d2e3f4a5b"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description No such workspace, **or** the caller is not a member of it. The two are
         *     deliberately indistinguishable: answering `403` for a workspace that
         *     exists but is not the caller's would let anyone enumerate tenants by
         *     guessing identifiers.
         */
        WorkspaceNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The caller is a member of this workspace but their role does not hold
         *     the required permission. Distinct from `404`, which hides the workspace
         *     entirely.
         */
        PermissionDenied: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The request conflicts with the resource's current state — a stale
         *     `version`, or a change that would leave the workspace with no owner.
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The invitation cannot be used.
         *
         *     Returned identically whether the token is unknown, expired, revoked or
         *     already accepted. Distinguishing them would tell someone guessing
         *     tokens which guesses were once real, turning a brute-force attempt
         *     into a search with feedback.
         */
        InvitationNotUsable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The body was malformed, carried unknown fields, or failed validation. */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request could not be completed. The failure is recorded against `request_id`. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description A dependency the request needs is temporarily unreachable — for
         *     example the identity provider's signing keys. The credential may be
         *     perfectly valid; it could not be checked. Safe to retry.
         */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        InstallationId: string;
        WorkspaceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspaces the caller belongs to, each with their role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Workspace"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description The created workspace. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    getWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace, with the caller's role and permissions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["WorkspaceNotFound"];
        };
    };
    renameWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    version: number;
                };
            };
        };
        responses: {
            /** @description The updated workspace, carrying its new version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["PermissionDenied"];
            404: components["responses"]["WorkspaceNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listWorkspaceInvitations: {
        parameters: {
            query?: {
                /** @description Narrow the list to one status. */
                status?: "pending" | "accepted" | "revoked" | "expired";
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every invitation for the workspace, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Invitation"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["PermissionDenied"];
            404: components["responses"]["WorkspaceNotFound"];
        };
    };
    issueWorkspaceInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    role: components["schemas"]["Role"];
                };
            };
        };
        responses: {
            /** @description The invitation, together with its token. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedInvitation"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["PermissionDenied"];
            404: components["responses"]["WorkspaceNotFound"];
            /** @description The address already belongs to the workspace, or already has an outstanding invitation. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeWorkspaceInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                invitationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invitation was withdrawn. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["PermissionDenied"];
            404: components["responses"]["WorkspaceNotFound"];
        };
    };
    previewInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationTokenRequest"];
            };
        };
        responses: {
            /** @description What the invitation offers, and nothing else about the workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPreview"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["InvitationNotUsable"];
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationTokenRequest"];
            };
        };
        responses: {
            /** @description The membership created by accepting. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        workspace_id: string;
                        role: components["schemas"]["Role"];
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            /** @description The invitation was issued to a different email address. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["InvitationNotUsable"];
            /** @description The caller already belongs to this workspace. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listWorkspaceMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every member of the workspace. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Member"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["WorkspaceNotFound"];
        };
    };
    removeWorkspaceMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["PermissionDenied"];
            404: components["responses"]["WorkspaceNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    changeWorkspaceMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role: components["schemas"]["Role"];
                };
            };
        };
        responses: {
            /** @description The updated membership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        user_id: string;
                        role: components["schemas"]["Role"];
                    };
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["PermissionDenied"];
            404: components["responses"]["WorkspaceNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    beginGitHubInstall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Where to send the browser. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        install_url: string;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["PermissionDenied"];
            404: components["responses"]["WorkspaceNotFound"];
        };
    };
    completeGitHubInstall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The single-use value GitHub echoed back. */
                    state: string;
                    /**
                     * Format: int64
                     * @description A claim, not a fact. It is confirmed with GitHub before
                     *     anything is written.
                     */
                    installation_id: number;
                };
            };
        };
        responses: {
            /** @description The installation is bound to the workspace. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Installation"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["PermissionDenied"];
            /**
             * @description The installation is already connected to a different workspace.
             *     Refused rather than rebound, because rebinding would move a
             *     repository grant between tenants.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listGitHubInstallations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The connected accounts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        installations: components["schemas"]["Installation"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["WorkspaceNotFound"];
        };
    };
    getGitHubInstallationHealth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The installation's current state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallationHealth"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["WorkspaceNotFound"];
        };
    };
    reconcileGitHubInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The recorded set now matches GitHub. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["PermissionDenied"];
            404: components["responses"]["WorkspaceNotFound"];
        };
    };
    listWorkspaceRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace's repositories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        repositories: components["schemas"]["Repository"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["WorkspaceNotFound"];
        };
    };
    createBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                repositoryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Required, and must begin with `weave/`. A caller that may
                     *     retry needs the same request to name the same branch —
                     *     generating one here would make each attempt create
                     *     another, which is the opposite of the idempotency below.
                     */
                    name: string;
                    /** @description The branch to create from. Defaults to the repository's default branch. */
                    base?: string;
                };
            };
        };
        responses: {
            /**
             * @description The branch already existed at the requested base. The same body,
             *     with `created: false` — a retry finding its own earlier work.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
            /** @description The branch was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            /**
             * @description The caller's role cannot manage repositories, the installation no
             *     longer grants the repository, the installation is suspended, the
             *     installation does not hold `contents: write`, or the target branch
             *     is protected.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description The workspace is not the caller's or does not exist, the repository
             *     was not found in it, or the requested base branch does not exist in
             *     the repository. The three are deliberately indistinguishable for
             *     the first two — a response confirming a workspace exists but is not
             *     yours turns identifier guessing into tenant enumeration.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description A branch of that name exists and points somewhere other than the
             *     requested base. Refused rather than returned, because handing back
             *     a branch at unknown work as though it were what was asked for is
             *     worse than an error.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    receiveGitHubWebhook: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description HMAC-SHA256 of the raw body. The SHA-1 header GitHub also sends is
                 *     deliberately ignored; honouring it would allow a downgrade to a
                 *     broken hash.
                 */
                "X-Hub-Signature-256": string;
                "X-GitHub-Delivery": string;
                "X-GitHub-Event": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /**
             * @description Applied, or deduplicated because it already was. Events naming an
             *     unknown installation and unrecognised event types also land here:
             *     both are deliberate no-ops, and failing them would make GitHub
             *     retry forever.
             */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The delivery was unreadable or lacked required headers. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The signature was absent, malformed, or did not match. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Another attempt holds this delivery and has not finished.
             *     Deliberately not acknowledged: GitHub does not retry what it
             *     believes succeeded, so answering 2xx here would discard the
             *     delivery if that attempt then failed.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Applying the delivery failed. GitHub retries, and the retry is
             *     processed rather than deduplicated away.
             */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
