// Package postgres implements the application's persistence ports against
// PostgreSQL, using queries generated by sqlc.
package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/jigmetnamgyal/weave/internal/adapters/postgres/postgresdb"
	"github.com/jigmetnamgyal/weave/internal/application"
	"github.com/jigmetnamgyal/weave/internal/domain"
)

// UserStore persists users in PostgreSQL.
type UserStore struct {
	queries *postgresdb.Queries
}

// compile-time check that the adapter satisfies the port.
var _ application.UserStore = (*UserStore)(nil)

// NewUserStore constructs a UserStore over a pgx pool.
func NewUserStore(pool *pgxpool.Pool) *UserStore {
	return &UserStore{queries: postgresdb.New(pool)}
}

// FindByExternalID returns the user for an identity-provider subject.
func (s *UserStore) FindByExternalID(ctx context.Context, externalID string) (domain.User, error) {
	row, err := s.queries.GetUserByExternalID(ctx, externalID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// Translate the driver's sentinel into the port's, so callers in
			// the application layer never import a database package.
			return domain.User{}, application.ErrUserNotFound
		}
		return domain.User{}, fmt.Errorf("select user by external id: %w", err)
	}
	return toDomain(row), nil
}

// UpsertByExternalID creates the user, or returns the existing row when the
// external ID is already present.
func (s *UserStore) UpsertByExternalID(ctx context.Context, user domain.User) (domain.User, error) {
	row, err := s.queries.UpsertUserByExternalID(ctx, postgresdb.UpsertUserByExternalIDParams{
		ID:          user.ID,
		ExternalID:  user.ExternalID,
		Email:       user.Email,
		DisplayName: optionalText(user.DisplayName),
		AvatarUrl:   optionalText(user.AvatarURL),
	})
	if err != nil {
		return domain.User{}, fmt.Errorf("upsert user by external id: %w", err)
	}
	return toDomain(row), nil
}

// toDomain converts a generated row into the domain entity.
func toDomain(row postgresdb.User) domain.User {
	return domain.User{
		ID:          row.ID,
		ExternalID:  row.ExternalID,
		Email:       row.Email,
		DisplayName: derefText(row.DisplayName),
		AvatarURL:   derefText(row.AvatarUrl),
		CreatedAt:   timestamp(row.CreatedAt),
		UpdatedAt:   timestamp(row.UpdatedAt),
	}
}

// optionalText maps an empty string to SQL NULL, so absent profile fields are
// stored as NULL rather than as an empty string that reads like a real value.
func optionalText(value string) *string {
	if value == "" {
		return nil
	}
	return &value
}

// derefText maps SQL NULL back to an empty string.
func derefText(value *string) string {
	if value == nil {
		return ""
	}
	return *value
}

// timestamp unwraps a pgtype timestamp, treating NULL as the zero time.
func timestamp(value pgtype.Timestamptz) time.Time {
	if !value.Valid {
		return time.Time{}
	}
	return value.Time
}
