package domain

import (
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// A runner is the execution environment a session runs in: an ephemeral,
// isolated sandbox holding a checkout of the session's branch. It is the first
// thing in Weave that executes what Weave did not write, and everything about
// it is decided by ADR-013 — see docs/adr/0013-runner-execution-boundary.md.

// RunnerState is where a runner is in its life.
type RunnerState string

// The states a runner passes through. Live states are the first three; a
// session may have at most one runner in any of them.
const (
	// RunnerProvisioning: the environment is being created and the checkout
	// made. Not yet ready.
	RunnerProvisioning RunnerState = "provisioning"
	// RunnerRunning: ready, and reported alive by its backend.
	RunnerRunning RunnerState = "running"
	// RunnerTerminating: teardown has begun. Recorded before the backend is
	// asked, so a crash mid-teardown leaves something to finish.
	RunnerTerminating RunnerState = "terminating"
	// RunnerTerminated: destroyed, in the ordinary way.
	RunnerTerminated RunnerState = "terminated"
	// RunnerFailed: destroyed after something went wrong. The reason says
	// what.
	RunnerFailed RunnerState = "failed"
)

// Live reports whether the runner may still exist in its backend.
func (s RunnerState) Live() bool {
	return s == RunnerProvisioning || s == RunnerRunning || s == RunnerTerminating
}

// Runner is one execution environment.
type Runner struct {
	// ID is generated by the control plane, never by the runner: it is what
	// binds the runner's events to its session.
	ID          uuid.UUID
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
	// Backend names the RunnerBackend that created it.
	Backend string
	// Handle is the backend's own name for it — a container id, a sandbox id.
	// Empty until the backend returns one.
	Handle        string
	State         RunnerState
	FailureReason string
	CreatedAt     time.Time
	ReadyAt       *time.Time
	TerminatedAt  *time.Time
}

// ErrRunnerNotFound is returned when no runner matches.
var ErrRunnerNotFound = errors.New("runner not found")

// NewRunnerID returns a sortable identifier for a runner.
func NewRunnerID() (uuid.UUID, error) {
	id, err := uuid.NewV7()
	if err != nil {
		return uuid.Nil, fmt.Errorf("generate runner id: %w", err)
	}
	return id, nil
}
